### ISSUE TITLE
drake/manipulation/kinova_jaco does not build

### ISSUE THREAD

**Issue by mpatalberta** [RobotLocomotion/drake#14544] opened 2021-01-19 21:12 UTC
I would expect a complete build to also do the complete code that is under the manipulation directory.
Thanks for your help

**Comment by jwnimmer-tri** [comment] 2021-01-19 21:17
Can you provide information on exactly what steps you performed, and what seemed to be missing afterwards or go wrong?

A quick skim of the source code, as well as the https://github.com/RobotLocomotion/drake/releases/tag/v0.25.0 precompiled images, shows me that the kinova_jaco libraries should be compiled under normal circumstances.

**Comment by jwnimmer-tri** [comment] 2021-01-21 17:10
I'm going to close this out as "needs more information".  Here's our stock information for how to get help -- https://drake.mit.edu/getting_help.html.

In this case, my best guess is that the software and build system are working as intended, but our documentation or tutorials are lacking or misleading, leading to some unexpected failure to build in your circumstances.  In that case, our preference is to use the community StackOverflow forum a with `#drake` tag to seek assistance in working through the build instructions.  If we find a documentation bug, we can return to the issue tracker here to consolidate it, but there's generally a larger community and better discussion forum on StackOverflow for support questions like this one.

If you are still having difficulty, please re-post this question to StackOverflow with more details.

**Closed by jwnimmer-tri** 2021-01-21 17:10 UTC
Labels: team: manipulation, type: user assistance

**Comment by mpatalberta** [comment] 2021-01-21 21:03
Jeremy,
My problem was not understanding what is going on.
The problem was not understanding the use of these files.
Pat.

**Comment by jwnimmer-tri** [comment] 2021-01-21 22:03
Sure thing, no problem.  We are eager to help support new users who have questions, but we'd like to host those discussions on the StackOverflow site, rather than the issues database here.

https://stackoverflow.com/questions/tagged/drake
