### ISSUE TITLE
 runQuadrotorDynamics  has timing issues in debug

### ISSUE THREAD

**Issue by billhoffman** [RobotLocomotion/drake#1982] opened 2016-04-01 17:48 UTC
https://drake-cdash.csail.mit.edu/testSummary.php?project=1&name=runQuadrotorDynamics&date=2016-04-01

It fails on various debug builds.  The output is similar for all failures:

welding base because it has no inertia beneath it
welding base because it has no inertia beneath it
welding base because it has no inertia beneath it
terminate called after throwing an instance of 'std::runtime_error'
  what():  Simulation is not keeping up with desired real-time factor -- behind by more than 1 (scaled) second at simulation time 0.350000

**Comment by jwnimmer-tri** [comment] 2016-04-01 17:55
Duplicate of #1920, I believe.

**Closed by jwnimmer-tri** 2016-04-01 17:55 UTC
