### ISSUE TITLE
rom pydrake.planning.common_robotics_utilities import SimpleRRTPlannerState Traceback (most recent call last):   File "<stdin>", line 1, in <module> ModuleNotFoundError: No module named 'pydrake.planning.common_robotics_utilities'

### ISSUE THREAD

**Issue by dbdxnuliba** [RobotLocomotion/drake#19347] opened 2023-05-04 02:09 UTC
### What happened?

>>> import multiprocessing as mp >>> from IPython.display import HTML, SVG >>> from pydrake.geometry import MeshcatVisualizer, MeshcatVisualizerParams, Role, StartMeshcat >>> from pydrake.geometry.optimization import IrisInConfigurationSpace, IrisOptions >>> from pydrake.multibody.parsing import LoadModelDirectives, Parser, ProcessModelDirectives >>> from pydrake.multibody.plant import AddMultibodyPlantSceneGraph >>> from pydrake.solvers import GurobiSolver, MosekSolver >>> from pydrake.planning.common_robotics_utilities import SimpleRRTPlannerState Traceback (most recent call last):   File "<stdin>", line 1, in <module> ModuleNotFoundError: No module named 'pydrake.planning.common_robotics_utilities' >>> import pydrake.planning >>> 

### Version

drake-1.13.0

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using CMake

### Relevant log output

```shell
cd /home/dell/ref/drake-1.13.0
mkdir drake-build
cd drake-build
cmake -DWITH_GUROBI=OFF  -DWITH_SNOPT=ON ..
make -j2

and after install suceesfully into /home/dell/ref/drake-1.13.0/drake-build/install

sudo gedit ~/.bashrc
#bazel related
source /home/taimi/.bazel/bin/bazel-complete.bash
export PATH=$PATH:$HOME/bin

export DRAKE_BUILD_DIR=$HOME/ref/drake-1.13.0/drake-build
export PYTHONPATH=${DRAKE_BUILD_DIR}/install/lib/python3.8/site-packages:${PYTHONPATH}


and then open a terminal with python
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import time
>>> import pickle
>>> import numpy as np
>>> import multiprocessing as mp
>>> from IPython.display import HTML, SVG
>>> from pydrake.geometry import MeshcatVisualizer, MeshcatVisualizerParams, Role, StartMeshcat
>>> from pydrake.geometry.optimization import IrisInConfigurationSpace, IrisOptions
>>> from pydrake.multibody.parsing import LoadModelDirectives, Parser, ProcessModelDirectives
>>> from pydrake.multibody.plant import AddMultibodyPlantSceneGraph
>>> from pydrake.solvers import GurobiSolver, MosekSolver
>>> from pydrake.planning.common_robotics_utilities import SimpleRRTPlannerState
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pydrake.planning.common_robotics_utilities'
>>> import pydrake.planning
>>> 
```
We can see the log above that issue occurs when type  
**from pydrake.planning.common_robotics_utilities import SimpleRRTPlannerState** 

but we don't have issue when type
 **import pydrake.planning**
So can you help me to fix the issue,thanks

**Comment by jwnimmer-tri** [comment] 2023-05-04 02:47
Closing as duplicate of #19346.

**Closed by jwnimmer-tri** 2023-05-04 02:47 UTC
Labels: type: bug
