### ISSUE TITLE
py systems: Bind unrestricted update

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10770] opened 2019-02-26 23:13 UTC
@avalenzu mentioned that he's not blocked by this, but would find it useful.

I also would've found it useful when prototyping a pure `rospy` subscriber block in `pydrake`.

**Comment by mpetersen94** [comment] 2020-03-26 15:53
During discussion of #12925, we realized that both the new `SystemSliders` and the `JointSliders` it is based off of are abusing the `Publish` method to update the GUI because the unrestricted update function that would be best for this purpose is not bound.  While these systems are just used for simple user interfacing, it sets a bad example for users that look into the source code.

**Comment by jwnimmer-tri** [comment] 2024-03-21 18:19
Closing as duplicate of #12059.

**Closed by jwnimmer-tri** 2024-03-21 18:19 UTC
Labels: type: feature request, priority: medium, component: pydrake
