### ISSUE TITLE
Should DirtranTrajectoryOptimization be deterministic?

### ISSUE THREAD

**Issue by eric-wieser** [RobotLocomotion/drake#1479] opened 2015-11-29 03:05 UTC
Because I'm finding that sometimes it generates a different trajectory when run multiple times on the same input.

However, I'm also getting occasional matlab crashes, so this could point to another Eigen memory alignment bug.

**Comment by eric-wieser** [comment] 2015-11-29 03:05
(also, does this belong here or on piazza?)

**Comment by RussTedrake** [comment] 2015-11-29 03:13
here is better than piazza.
others can confirm, but I believe that our understanding is that snopt stores hidden state which can make things non-deterministic.

**Comment by hongkai-dai** [comment] 2015-11-29 03:13
The random result could be caused by SNOPT. If you run
checkDependency('snopt'), and it does not print out any error, then SNOPT
is used as the nonlinear solver. After every call of SNOPT, it caches some
result from the current run (such as the active set, basic variables, etc),
and uses those cached results in the next run. This cached result would
make two consecutive calls of SNOPT to generate two different result, even
on the same problem. To avoid such randomness, make sure you call 'make
classes' or 'megaclear' every time after you call
DirtranTrajectoryOptimization. This will erase the cached result.

**Comment by hongkai-dai** [comment] 2015-11-29 03:18
Sorry, it should be 'clear classes' instead of 'make classes'

**Comment by RussTedrake** [comment] 2015-11-29 03:31
thanks @hongkai-dai .  reading your answer it occurred to me that the crashes might be coming from snopt, too.  it's known that if you hit ctrl-c when you're inside the snopt mex, then it will crash on the next run, unless you run something like megaclear.

**Comment by eric-wieser** [comment] 2015-11-29 06:37
I'm still getting very non-deterministic behaviour (after using `megaclear`). Here's one run of my optimization:

![image](https://cloud.githubusercontent.com/assets/425260/11455692/7243a426-9639-11e5-94bd-4e4e139da3d7.png)

And here's another

![image](https://cloud.githubusercontent.com/assets/425260/11455694/9f153b90-9639-11e5-8518-292ec8a9035f.png)

I don't call `rand` anywhere in my code. Interestingly, the blue line has a constraint to stay on a straight line. This seemed to succeed when run on a fresh matlab instance, but evidently no longer does

**Comment by eric-wieser** [comment] 2015-11-29 06:40
To prove I'm not going insane, closing all the figure windows and trying again gave me this (more expected) result:

![image](https://cloud.githubusercontent.com/assets/425260/11455701/1ec6a90a-963a-11e5-8988-067f8a5c0fa4.png)

**Comment by tkoolen** [comment] 2015-11-30 15:21
Just to be a little more certain that none of the code you're calling is using anything random, could you try
```
dbstop in rand
dbstop in randn
dbstop in randi
dbstop in sprand
dbstop in sprandn
dbstop in randperm
```
and then run your code?

**Comment by eric-wieser** [comment] 2015-12-01 06:17
Thanks, I think that caught it - I wasn't passing `solveTraj(obj,t_init,traj_init)` its last two arguments

**Comment by tkoolen** [comment] 2015-12-01 19:16
You're welcome, good to hear.

**Comment by tkoolen** [comment] 2015-12-03 21:31
Close the issue?

**Closed** 2015-12-03 21:57 UTC
