### ISSUE TITLE
documentation for get_generalized_contact_forces_output_port gives no indication of what the format/type of the output is

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9393] opened 2018-09-06 11:30 UTC
http://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1multibody__plant_1_1_multibody_plant.html#a1d355c7fc6c5c09a52e9fd8daf026ddf

The only way I know how to infer it is by digging into the source code.

**Comment by RussTedrake** [comment] 2018-09-06 11:32
(and it looks like a BasicVector of size num_velocities, which puzzles me)

**Comment by jwnimmer-tri** [comment] 2024-03-20 02:33
Duplicate of #13146.

**Closed by jwnimmer-tri** 2024-03-20 02:33 UTC
Labels: priority: low, type: documentation, component: multibody plant
