### ISSUE TITLE
port changeRootLink functionality to C++

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/drake#2293] opened 2016-05-09 15:01 UTC
currently the changeRootLink functionality #417 is only in matlab. Now that we have Valkyrie we have pelvis and back mounts for testing. Since the pelvis is the root link we can only have a fixed pelvis model in Drake. For testing purposes it would be good to have a fixed back model as well.

Discussed this briefly with @RussTedrake @tkoolen. Assigning to myself for now but would like to hand this off.

_Update from @liangfok:_ The MATLAB implementation is here: https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/systems/plants/%40RigidBodyManipulator/changeRootLink.m

**Comment by liangfok** [comment] 2016-05-09 15:21
As a quicker workaround, couldn't we simply modify the SDF / URDF to make the torso the parent of the pelvis rather than the other way around?

**Comment by manuelli** [comment] 2016-05-09 15:29
I'm not sure that is so easy because there are lots of offsets and rotations in the urdf specification that are specific to the ordering that is given.

**Comment by RussTedrake** [comment] 2016-05-09 21:46
Plus we want to keep compatibility with the urdfs used by the other Val teams.

**Comment by RussTedrake** [comment] 2016-05-27 05:15
for reference, the matlab implementation is here:
https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/%40RigidBodyManipulator/changeRootLink.m

**Comment by liangfok** [comment] 2016-05-27 10:20
Sorry I'm still trying to understand. Isn't the "root link" of a robot defined by the link to which we attach the virtual floating joint? If so, couldn't we make the torso the root link by simply attach the floating joint to the torso rather than the pelvis?

**Comment by tkoolen** [comment] 2016-05-27 19:18
Unfortunately it's not quite that trivial. The problem is that there are various objects associated with rigid bodies, like visuals, collision objects, etc. The pose of these objects (both in the URDF and in our RigidBodyTree) is defined *with respect to the frame after the parent joint*. If you change the root link, then some parent joints may flip direction and become child joints. So you have to change the pose of all the objects that are associated with a rigid rigid body if its parent joint flips direction.

I think the long term solution should be to take all of the objects currently associated with rigid bodies and instead associate them with frames. Then you would only have to change the definition of that frame, instead of having to keep track of all of those objects and transform them individually. But again that's longer term and it would be good to get this soon.

**Comment by sherm1** [comment] 2016-05-27 19:53
Also longer term: IMO it is a shame to get the links and joints mixed up with their (non-unique) representation as an internal coordinate tree. Links and joints and the meaning of joint coordinates are all very user-relevant, while the internal model ought not to be. The same user-facing behavior is achievable with maximal coordinates or a variety of minimal coordinate representations.

**Comment by tkoolen** [comment] 2016-05-27 20:21
Yep, completely agree with that.

**Comment by liangfok** [comment] 2016-05-27 20:23
Thanks for the explanation and longer term solution! It makes sense.

**Comment by liangfok** [comment] 2017-03-09 19:24
I recommend that this feature be implemented in `MultiBodyTree` rather than `RigidBodyTree`.

\CC: @amcastro-tri

**Comment by tri-ltyyu** [comment] 2019-03-22 18:23
This is likely specific to RigidBodyPlant. If this is applicable to MultBodyPlant/SceneGraph, please file new issue. Closing for now.

**Closed by tri-ltyyu** 2019-03-22 18:23 UTC
Labels: priority: medium, team: dynamics, type: feature request
