### ISSUE TITLE
Sporadic (but rare) failures due to `bad interpreter: Text file busy`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8651] opened 2018-04-20 19:23 UTC
The following CI build failed:
https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-xenial-gcc-bazel-continuous-mosek-release-550&field2=buildstarttime&compare2=84&value2=now

The error was:
```
simple_powertrain_cpplint: /usr/bin/env: bad interpreter: Text file busy
```

The build was restarted and passed.

**Comment by m-chaturvedi** [comment] 2018-07-11 15:54
[Bazel discussion](https://groups.google.com/forum/#!topic/bazel-discuss/rX36q1tOxEg)
>Issued a pull request here: https://github.com/bazelbuild/bazel/pull/5556, please comment with any +1s and excitement for the fix.

**Comment by jwnimmer-tri** [comment] 2018-11-14 15:42
Duplicate of #9040 per Eric.

**Closed by jwnimmer-tri** 2018-11-14 15:42 UTC
Labels: configuration: mac, team: kitware, type: continuous integration
