### ISSUE TITLE
controlled_iiwa_world_demo does not knock down all targets

### ISSUE THREAD

**Issue by Lucy-tri** [RobotLocomotion/drake#5092] opened 2017-02-07 22:05 UTC
The controlled_iiwa_world_demo has comments indicating that it knocks down all 3 cylinders on it's table, however, when I built, it only knocked down the center cylinder. 

Consider creating a test that each cylinder is in fact knocked over (perhaps check their final resting place at the end of the simulation run).
Sam duplicated this with cmake, I built using Bazel.

**Comment by naveenoid** [comment] 2017-02-22 22:27
I will sort this out as soon as my bazel build issues settle (hopefully in next couple of days). Your suggestion for a test on cylinder state is worth implementing.

**Comment by naveenoid** [comment] 2017-03-02 17:08
Ok since Siyuans controller update #5339 it does seem to be the case that all targets are knocked over. I can add a test anyhow.

**Comment by sammy-tri** [comment] 2019-03-04 19:59
The demo has been deleted, along with the associated comment.  The functionality does not appear to have been reproduced anywhere else.  Closing as there's nothing left to do.

**Closed by sammy-tri** 2019-03-04 19:59 UTC
Labels: team: manipulation, type: bug
