### ISSUE TITLE
Add gflags as a required external dependency and make use of it in Drake's executables

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3027] opened 2016-08-02 03:28 UTC
One of the first places to use it would be in `drake-distro/drake/examples/Cars/car_simulation.cc`.

**Comment by sherm1** [comment] 2016-08-02 04:24
:+1: great idea!

**Comment by david-german-tri** [comment] 2016-08-02 14:20
:+1: gflags would also supersede `drakeAppUtil.h`.  (Closed #1768 as a duplicate of this issue.)

**Comment by jwnimmer-tri** [comment] 2016-08-18 02:09
I've filed a PR to attempt this, though I ported an LCM test program, not the (more complicated) cars example.

I kind of hate the `gflags` global variable meme; the composeability of `boost::program_options` is much superior IMO, but perhaps this will grow on me.  In any case, it's better than `drakeAppUtil.h`.

**Closed** 2016-08-18 19:19 UTC
Labels: priority: medium, team: software core, type: feature request
