### ISSUE TITLE
Mysterious CI Error - could not lock config file

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4034] opened 2016-11-04 23:37 UTC
# The Error

```
15:10:33 Cloning into 'drake/doc/textbook'...
15:10:33 Submodule path 'drake/doc/textbook': checked out 'e051917c15a513e1924465060134164c85fe5141'
15:10:33 error: could not lock config file /home/ubuntu/workspace/linux-gcc-ninja-continuous-matlab-debug/.git/modules/drake/doc/textbook/config: File exists
15:10:33 Failed to register url for submodule path 'HTMLBook'
15:10:33 Failed to recurse into submodule path 'drake/doc/textbook'
```

# Example Console Logs

* https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-gcc-ninja-continuous-matlab-debug/379/consoleFull

**Comment by jwnimmer-tri** [comment] 2016-11-05 00:00
A prior example:
https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=169296
```
Cloning into 'externals/xfoil'...
error: could not lock config file /home/ubuntu/workspace/linux-gcc-ninja-experimental/.git/modules/externals/xfoil/config: File exists
```

**Comment by jwnimmer-tri** [comment] 2016-11-08 15:47
This happens up to a few times per week or more.  Let get it onto Kitware's radar.

**Comment by david-german-tri** [comment] 2016-11-08 16:34
I have yet to be inconvenienced myself, but @jamiesnape @BetsyMcPhail, PTAL?

**Comment by liangfok** [comment] 2016-11-21 20:40
@hongkai-dai experienced this here:
https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-experimental-open-source-debug/804/console

**Comment by jwnimmer-tri** [comment] 2016-11-22 20:16
Again
https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-continuous-matlab-debug/494/

**Comment by jamiesnape** [comment] 2016-11-22 20:24
Has anyone observed this on a non-Ninja build?

**Comment by liangfok** [comment] 2016-11-29 11:36
I just experienced this issue here:
https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-experimental/1170/

**Comment by Lucy-tri** [comment] 2016-11-30 21:10
Failing with snopt: linux-clang-ninja-continuous-debug-pre-drake
Cloning into 'externals/snopt'...
error: could not lock config file /home/ubuntu/workspace/linux-clang-ninja-continuous-debug/.git/modules/externals/snopt/config: File exists
(https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-clang-ninja-continuous-debug/1061/ )

**Comment by jwnimmer-tri** [comment] 2016-12-01 02:45
Again
https://drake-jenkins.csail.mit.edu/job/linux-clang-ninja-experimental-open-source/1166/

**Comment by liangfok** [comment] 2016-12-05 03:59
Again: https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-experimental/1365/console

**Comment by liangfok** [comment] 2016-12-05 11:10
Again: https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-experimental/1368/console

**Comment by liangfok** [comment] 2016-12-05 13:57
Again: https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-experimental/1372/

**Comment by liangfok** [comment] 2016-12-06 14:13
Again: https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-experimental/1431/

**Comment by jamiesnape** [comment] 2016-12-06 14:43
We have enough information now and are trying to reproduce. Post if there is a failure that is not Linux and Ninja.

**Comment by mwoehlke-kitware** [comment] 2016-12-13 18:57
RobotLocomotion/drake-ci#62 will hopefully give us some information if it happens again, and should also work around the problem by retrying the failed git command. Builds that have git errors should show as 'unstable'. (For build-cop purposes, these can be treated as "clean", but the strace output should be inspected for clues.)

**Comment by SeanCurtis-TRI** [comment] 2017-01-10 14:51
This cropped up [again](https://drake-cdash.csail.mit.edu/viewBuildError.php?onlydeltap&buildid=301801).  This time affecting `libccd`.  Per @jamiesnape's request, this is in a mac build.

**Comment by liangfok** [comment] 2017-01-10 15:11
@SeanCurtis-TRI can you provide a link to the console log or CI build page?

**Comment by SeanCurtis-TRI** [comment] 2017-01-10 15:12
Sorry, here you go: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-clang-ninja-nightly-minimal-debug/160/

**Comment by jamiesnape** [comment] 2017-01-10 15:13
(Aside: CDash links persist longer than Jenkins links)

**Comment by SeanCurtis-TRI** [comment] 2017-01-10 15:22
I suspected that might be the case, which is why the original posting used a cdash link.

**Comment by mwoehlke-kitware** [comment] 2017-01-10 18:17
The build should not have failed outright, however. Looking closer, there are issues *other than* the "could not lock config file" problem:

```
[9/46] cd /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug && "/usr/local/Cellar/cmake/HEAD-ce71bd9/bin/ctest" --launch --target-name TARGET_NAME --build-dir /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build --output /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build/CMakeFiles/submodule-sync --  /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/ci/tools/git-wrapper.bash submodule --quiet sync --
fatal: Not a git repository: /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/.git/modules/externals/ccd
fatal: Not a git repository: /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/.git/modules/externals/ccd
[10/46] cd /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug && "/usr/local/Cellar/cmake/HEAD-ce71bd9/bin/ctest" --launch --target-name TARGET_NAME --build-dir /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build --output /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build/ccd-prefix/src/ccd-stamp/ccd-download --  /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/ci/tools/git-wrapper.bash submodule update --init --recursive -- externals/ccd && "/usr/local/Cellar/cmake/HEAD-ce71bd9/bin/ctest" --launch --target-name TARGET_NAME --build-dir /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build --output /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build/ccd-prefix/src/ccd-stamp/ccd-download --  /usr/local/Cellar/cmake/HEAD-ce71bd9/bin/cmake -E touch /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build/ccd-prefix/src/ccd-stamp/ccd-download
FAILED: ccd-prefix/src/ccd-stamp/ccd-download 
cd /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug && "/usr/local/Cellar/cmake/HEAD-ce71bd9/bin/ctest" --launch --target-name TARGET_NAME --build-dir /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build --output /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build/ccd-prefix/src/ccd-stamp/ccd-download --  /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/ci/tools/git-wrapper.bash submodule update --init --recursive -- externals/ccd && "/usr/local/Cellar/cmake/HEAD-ce71bd9/bin/ctest" --launch --target-name TARGET_NAME --build-dir /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build --output /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build/ccd-prefix/src/ccd-stamp/ccd-download --  /usr/local/Cellar/cmake/HEAD-ce71bd9/bin/cmake -E touch /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/build/ccd-prefix/src/ccd-stamp/ccd-download
Cloning into 'externals/ccd'...
error: could not lock config file /Users/elcapitan/workspace/mac-clang-ninja-nightly-minimal-debug/.git/modules/externals/ccd/config: File exists
fatal: Could not set 'remote.origin.url' to 'https://github.com/danfis/libccd.git'
fatal: clone of 'https://github.com/danfis/libccd.git' into submodule path 'externals/ccd' failed
Cloning into 'externals/ccd'...
Submodule path 'externals/ccd': checked out '16b9379fb6e8610566fe5e1396166daf7106f165'
```

The failure despite succeeding on retry is due to a stupid logic error in the wrapper, fixed by RobotLocomotion/drake-ci#70. What is interesting however are the errors from the `submodule sync` attempt, which makes me wonder if *all* the "could not lock config file" errors are merely symptomatic of something having gone wrong earlier...

**Comment by liangfok** [comment] 2017-01-10 18:22
Great job sleuthing!

**Comment by liangfok** [comment] 2017-01-17 18:38
https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-experimental-open-source-debug/2463

**Comment by liangfok** [comment] 2017-01-26 16:00
https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-experimental/2824/

**Comment by liangfok** [comment] 2017-02-06 01:51
https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-ninja-experimental-open-source/308/

**Comment by jwnimmer-tri** [comment] 2017-03-05 23:20
Demoting high -> medium, because the git retry logic is helping, and because in BazelDrake land we won't be shelling out to git commands for submodules anymore.

**Comment by liangfok** [comment] 2017-03-06 17:14
https://drake-jenkins.csail.mit.edu/job/linux-xenial-cpplint-experimental/1038/

**Comment by liangfok** [comment] 2017-03-09 02:58
https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-ninja-experimental-open-source/1609/

**Comment by liangfok** [comment] 2017-03-13 22:12
https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-ninja-experimental-open-source-debug/1711/

**Comment by liangfok** [comment] 2017-03-22 11:36
https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-ninja-experimental/1982/

**Comment by liangfok** [comment] 2017-03-26 03:36
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-gcc-ninja-continuous-release/393/

**Comment by liangfok** [comment] 2017-03-30 16:50
https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-ninja-experimental-open-source-debug/2314/

**Comment by liangfok** [comment] 2017-04-02 04:20
https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-ninja-experimental/2351/

**Comment by liangfok** [comment] 2017-04-15 01:45
https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-ninja-experimental-minimal/2836/

**Comment by liangfok** [comment] 2017-05-31 18:17
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-gcc-ninja-continuous-release/759/

**Comment by liangfok** [comment] 2017-09-26 13:35
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-clang-ninja-continuous-release/1336/

**Closed** 2017-09-29 19:10 UTC
Labels: configuration: cmake, priority: medium, team: kitware, type: bug, type: continuous integration
