### ISSUE TITLE
Visualization is Broken in Manipulation Station

### ISSUE THREAD

**Issue by maggi3wang** [RobotLocomotion/drake#11963] opened 2019-08-26 19:50 UTC
Running `bazel run //examples/manipulation_station:end_effector_teleop_sliders --config gurobi` leads to a seemingly broken visualization. 

Here is the view in meshcat:
<img width="1440" alt="Screen Shot 2019-08-26 at 3 34 53 PM" src="https://user-images.githubusercontent.com/5004244/63718628-fc596c80-c818-11e9-8910-f2b923982c37.png">

Replicated using the `drake_visualizer` tool:
<img width="1431" alt="Screen Shot 2019-08-26 at 3 39 37 PM" src="https://user-images.githubusercontent.com/5004244/63718597-eb106000-c818-11e9-8863-181e06efbbac.png">

Off the latest master. Running on MacOS (Mojave 10.14.5).

**Comment by maggi3wang** [comment] 2019-08-29 03:26
I ran a bisect that showed that `Updates geometry::Identifier hash method (#11872)` (commit `861cd550e79f9a952cb529bc8f7c94cbbcc1e40b`) is where this issue first occurred. Not sure why, though—any ideas?

**Comment by jwnimmer-tri** [comment] 2019-08-29 11:46
@maggi3wang Thank you!

Per the above posts, the problem seems to relate to an `unordered_map` use.  The hash method in #11872 changes how items added to the unordered_map are assigned to buckets, and thus their iteration order.  So while #11872 is probably a necessary condition to reproduce this bug, the root cause logic error would be in some other code.

Looking at the code that Greg identified, I can say that `SceneGraph<T>::CalcPoseBundle` is defective currently.  It assumes that `PoseBundle<T>* output` is in some semi-constructed state when the method begins.  That is defective with in the systems framework.  It is the responsibility of `CalcPoseBundle` ensure `*output` has the correct value upon return, no matter its incoming value.  It is an `@param[out]` only, not `@param[in,out]`.

I don't know if that defect is the cause of this issue, but maybe it's somewhere to begin.

**Comment by SeanCurtis-TRI** [comment] 2019-08-29 14:05
I agree with @jwnimmer-tri's characterization of the defect.

I've created a PR to address the issue (#11978) . @maggi3wang please confirm that this alleviates woes on the mac.

As a side note: I've got a branch where I'm changing the visualization mechanism to not rely on `PoseBundle` at all. So, when that gets up and running, this whole mechanism will be deprecated.

**Comment by maggi3wang** [comment] 2019-08-29 17:04
@SeanCurtis-TRI  #11979 worked on the Mac. Thanks!

**Comment by SeanCurtis-TRI** [comment] 2019-08-29 21:52
Huzzah! Thanks for all the sleuthing, @maggi3wang.

**Closed** 2019-08-30 13:27 UTC
Labels: configuration: mac, team: robot locomotion group
