### ISSUE TITLE
Three fem/dev tests failing valgrind

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#14312] opened 2020-11-10 17:08 UTC
For reference  (thanks, Jeremy): https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-nightly-valgrind-memcheck/725/

```
//multibody/fem/dev:fem_elasticity_test                                  FAILED in 2.2s
//multibody/fem/dev:fem_state_test                                       FAILED in 1.7s
//multibody/fem/dev:linear_elasticity_model_cache_test                   FAILED in 2.3s
```
These tests were temporarily switched to manual in #14311.

These should be fixed right away and re-enabled, please -- typically valgrind catches real problems like references to uninitialized memory.
cc @xuchenhan-tri @amcastro-tri

**Comment by xuchenhan-tri** [comment] 2020-11-11 00:42
The issue is resolved by PR #14313.

**Closed** 2020-11-11 00:42 UTC
Labels: component: multibody plant, priority: high, team: dynamics, type: bug
