### ISSUE TITLE
Include all example binaries in the Drake install

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#4224] opened 2016-11-22 19:24 UTC
This matters, for instance, to KUKA users.

cc @patmarion

**Comment by jamiesnape** [comment] 2016-11-22 19:26
Also useful for #1766.

**Comment by patmarion** [comment] 2017-03-24 14:04
I would still like to see this happen in the CMake build.  But if there's no plans to do so, please close this issue.

**Comment by jwnimmer-tri** [comment] 2017-03-24 14:19
I think the issue is still valid even some CMake listfiles are going away -- the Bazel binary release could / should include those artifacts.

**Comment by david-german-tri** [comment] 2017-03-24 18:11
I am going to bump the priority down to medium, though.

**Comment by EricCousineau-TRI** [comment] 2018-02-08 04:41
Closing, given that Francois's PRs for a subset of examples have landed.

**Comment by jwnimmer-tri** [comment] 2018-02-08 12:07
I thought the goal was to install ~all examples?

**Comment by jamiesnape** [comment] 2018-02-08 14:12
It is.

**Comment by jwnimmer-tri** [comment] 2020-09-16 03:15
We don't seem to be suffering for not having this since the past four years, and adding more C++ binaries would only increase the image footprint when most users just want the library, not the demos.  Using online notebooks for the demos seems to be the way of the future.

Unless anyone speaks up about this in the next month or two, we'll plan to close this as "won't fix".

**Closed** 2020-12-09 23:53 UTC
Labels: component: distribution, priority: backlog, team: kitware
