### ISSUE TITLE
drake_visualizer on Ubuntu 16.04

### ISSUE THREAD

**Issue by vmatos** [RobotLocomotion/drake#2624] opened 2016-06-23 10:34 UTC
Hello!
Is anyone running the binary distribution on Ubuntu 16.04?

```
~/libraries/drake-distro/build/bin$ ./drake-visualizer 
./drake-visualizer: error while loading shared libraries: libvtkPythonCore.so.5.8: cannot open shared object file: No such file or directory
```

I can't `sudo apt-get install python-vtk`, because it will try to remove my ROS packages.

I tried to compile from source, but it also stops when it reaches:

```
[ 78%] Performing configure step for 'director'
loading initial cache file /home/vmatos/experiments/drake-distro/externals/director/distro/pods/drake-distro/pod-build/tmp/director-cache-Release.cmake
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.
```

On a side note. Is there any place to discuss topics not related to the development of drake?

**Comment by liangfok** [comment] 2016-06-23 13:30
> I can't sudo apt-get install python-vtk, because it will try to remove my ROS packages.

Which ROS packages are conflicting with `python-vtk`?

> On a side note. Is there any place to discuss topics not related to the development of drake?

None that I'm aware of. Are you looking for a "Drake User's Forum"?

**Comment by vmatos** [comment] 2016-06-23 13:48
Yes! Something like a "Drake User's Forum".

`python-vtk` conflicts with `python-vtk6`, which lots of things depend on it.

```
$ apt-cache depends python-vtk6
python-vtk6
  Depends: libvtk6.2
(...)
  Conflicts: python-vtk
(...)

$ apt-cache rdepends python-vtk6
python-vtk6
Reverse Depends:
  libvtk6-dev
(...)

$ apt-cache rdepends libvtk6-dev
libvtk6-dev
Reverse Depends:
  (...)
  libpcl-dev

$ apt-cache rdepends libpcl-dev
libpcl-dev
Reverse Depends:
  libpcl-conversions-dev
  ros-kinetic-rtabmap
  ros-kinetic-pcl-ros
  ros-kinetic-pcl-conversions
(...)
```

**Comment by liangfok** [comment] 2016-06-23 15:10
Unfortunately, I think this github issue tracker is the closest thing we have right now to a Drake User's Forum. 😢 

Regarding the `python-vtk` vs. `python-vtk6` issue, I believe Drake Visualizer is based on Director, which currently uses VTK 5 (https://github.com/RobotLocomotion/drake/issues/1786#issuecomment-191497215). We are in the process of updating it to use VTK7 (https://github.com/RobotLocomotion/drake/issues/2628). Unfortunately, I'm not sure if that will also conflict with VTK 6 (which is what you're using). 

Do you know if VTK 6 and 7 can peacefully coexist?

**Comment by vmatos** [comment] 2016-06-23 15:14
I don't know how to answer your question.

As far as I understand, only VTK6 is available through ubuntu's repositories.

**Comment by liangfok** [comment] 2016-06-23 15:24
I will be installing ROS + Drake in an Ubuntu 16.04 machine soon. Will let you know if I encounter this problem and if I find a work around.

**Comment by liangfok** [comment] 2016-06-23 18:34
I confirm I'm running into the same problem when I try to install ROS with Drake on Ubuntu 16.04.

```
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist. 
```

**Comment by liangfok** [comment] 2016-06-24 12:36
I just wanted to clarify that I marked this issue as "low priority" because Ubuntu 16.04 + ROS is not on the list of [officially supported platforms](http://drake.mit.edu/developers.html#supported-configurations). We'll resolve it as time permits.

**Comment by david-german-tri** [comment] 2016-09-22 14:28
I think this is resolved in the Ubuntu 16.04 install instructions.  (Still not officially supported, but we're getting there!)  If it still doesn't work for you, feel free to reopen.

http://drake.mit.edu/ubuntu_xenial.html

**Comment by liangfok** [comment] 2016-10-06 03:16
I just installed Drake on a clean Ubuntu 16.04 followed by ROS Kinetic and ran into this issue. I will thus re-open it. I believe the problem is Drake Visualizer requires `libvtk5-dev` to be installed whereas ROS Kinetic requires `libvtk6-dev`.

**Comment by liangfok** [comment] 2016-10-06 03:31
I suspect `libvtk6-dev` is installed by ROS because ROS Kinetic requires PCL 1.7.x, which is provided by package `libpcl-dev`, which depends on `libvtk6-dev`.

http://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021

**Comment by RussTedrake** [comment] 2016-10-06 09:53
fyi @patmarion

**Comment by patmarion** [comment] 2016-10-06 11:38
I think that the best option for right now is to have users of ubuntu 16 and ros Kinetic (who are required to apt-get install vtk6) compile vtk5 from source.  The director superbuild already supports this mode. In the cmake configure, just switch USE_SYSTEM_VTK to OFF (it defaults to ON).  When USE_SYSTEM_VTK is OFF, the director superbuild will clone and compile vtk5.

**Comment by patmarion** [comment] 2016-10-06 11:43
To make this work more smoothly for users, we could submit a PR to director to update its superbuild system: instead of defaulting to USE_SYSTEM_VTK=ON, first check that vtk5 is actually installed, and if it isn't then default USE_SYSTEM_VTK=OFF.

**Comment by jwnimmer-tri** [comment] 2016-12-22 18:21
Mission accomplished.

**Closed by jwnimmer-tri** 2016-12-22 18:21 UTC
Labels: configuration: linux, priority: low, team: kitware, type: bug, type: installation and distribution
