### ISSUE TITLE
Migrate APIs to MBP. Make MBT "internal::". Deprecate MBP::tree()

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#9694] opened 2018-10-17 13:43 UTC
Per discussion at Ann Arbor on-site. The objective is to stabilize our APIs as quickly as possible.

**Comment by tri-ltyyu** [comment] 2018-11-09 22:21
Duplicate of https://github.com/RobotLocomotion/drake/issues/9366 which has more context. Closing this one for #9366

**Closed by tri-ltyyu** 2018-11-09 22:21 UTC
Labels: priority: high, team: dynamics
