### ISSUE TITLE
Update Drake's URDF Parser to Treat World Links as part of the Model and Not Anything Special

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3081] opened 2016-08-08 01:47 UTC
Drake's URDF parser currently treats bodies called "world" as a special rigid body that represents the world within a `RigidBodyTree` (see: https://github.com/RobotLocomotion/drake/issues/2168).  This unfortunately, does not match the semantics used by RViz, which I believe is "official" since RViz is made by the same community that invented URDF. Unlike Drake, RViz treats "world" bodies within a URDF like any other body in the model, as shown in the screenshot below:

![screenshot from 2016-08-07 21 22 34](https://cloud.githubusercontent.com/assets/1388098/17466956/b81b7194-5ce6-11e6-9a3a-0b82d354ff9f.png)

The screenshot shows what happens when a [URDF of the Stata garage](https://github.com/RobotLocomotion/drake/blob/master/ros/drake_cars_examples/models/stata_garage_p1.urdf), which has a "world" body, is loaded into RViz. Note that the "world" body within the URDF model is treated just like any other body in the model, as indicated by the "stata_garage/world" body. (Note that the name is namespaced by the model name "stata_garage". This is necessary to support multiple models within the same `/tf` tree. See below for an explanation.)

The screenshot above also shows that there is a missing transform from "stata_garage/world" to "world". This is because Drake is using an [SDF model of the Stata garage](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Cars/models/stata_garage_p1.sdf), which doesn't have a world link. One solution to the problem is to have Drake load the same model as RViz. Unfortunately, Drake can't currently load the Stata garage URDF because Drake will combine the "world" body with the actual world body and abort after it detects more than one model in the URDF that branches from the URDF's "world" body. Below is the error that Drake prints when it attempts to load the URDF of the Stata Garage:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR: Model contains multiple joints that connect to world!
```

We did not previously detect the above discrepancy between Drake and RViz because multiple models was not supported, meaning the `/tf` frame names did not have a prefix. Thus, the "world" in the Stata garage model exactly matched the official "world" in RViz. Now that Drake is being modified to support multiple models, we need to namespace the transform names to avoid confusion caused by multiple models sharing the `/tf` frame names.

**Comment by liangfok** [comment] 2016-08-08 02:54
Note that work cannot begin on this issue until after #3064 is merged, since that PR enables multi-model support in `RigidBodySystem` and `RigidBodyTree`.

**Comment by liangfok** [comment] 2016-08-12 00:43
After exchanging a few e-mails with OSRF, the observations in this issue are correct. RViz does not maintain "world" as a keyword. Thus, a link called "world" is treated like anyother link in the URDF. Because of this, I believe this issue should remain open.

Longer term, we should do one or more of the following:

1. Modify [Transform Broadcaster](http://wiki.ros.org/tf/Tutorials/Writing%20a%20tf%20broadcaster%20(C%2B%2B)), [RViz](http://wiki.ros.org/rviz), and the rest of ROS to support SDF.

2. Extend SDF to support the inclusion of URDF models as first-class elements.

3. Extend URDF to include `<world>` as a first class tag.

**Comment by liangfok** [comment] 2016-08-12 04:05
Here are some more notes:

Gazebo uses keyword "world". Here's an example joint attaching link utorso to the world:

https://bitbucket.org/osrf/drcsim/src/194be8500fef81593f79607a21ee2badd9700a0e/atlas_description/urdf/atlas_harnessed.gazebo?at=default&fileviewer=file-view-default#atlas_harnessed.gazebo-12

Here is WIP on adding a `<world>` element to URDFs: https://github.com/ros/urdfdom_headers/tree/master/urdf_world/include/urdf_world

URDF could be generalized to allow multiple models in a single file. For example:

```
<?xml version="1.0" ?>
<robot name="robot_foo">
  <origin xyz="..." rpy="..."/>
  <link name="world" />
  ...
</robot>
<robot name="robot_bar">
  <origin xyz="..." rpy="..."/>
  <link name="world" />
  ...
</robot>

<robot name="robot_baz">
  <origin xyz="..." rpy="..."/>
  <link name="world" />
  ...
</robot>
```

SDF already assumes this format:

```
<world>
  <model name="m1">
  </model>
  <model name="m2">
  </model>
  ...
</world>
```

SDF also supports include directives:

```
<?xml version="1.0" ?>
<sdf version="1.5">
  <world name="default">
    <include>
      <uri>model://double_pendulum_with_base</uri>
    </include>
    <include>
      <uri>model://double_pendulum_with_base</uri>
      <pose>1 1 0 0 0 0</pose>
    </include>
    <model name="m1">
   ...
    </model>
  </world>
</sdf>
```

One high priority item is to modify the SDF standard to be able to include URDFs:

```
<world>
  <model name="m1">
     [SDF]
  </model>
  <model type="urdf" name="u1">
    [URDF]
  </model>
</world>
```

**Comment by liangfok** [comment] 2016-08-12 04:21
To weld a model to the world using SDF, one currently does the following:

```
<?xml version="1.0" ?>
<sdf version="1.5">
  <world name="default">
    <model name="pendulum_welded_base">
      <include>
        <uri>model://double_pendulum_with_base</uri>
      </include>
      <joint name="pendulum_world" type="fixed">
        <child>double_pendulum_with_base::base_link<child>
        <parent>world</parent>
      </joint>
    </model>
  </world>
</sdf>
```

A possible extension is to allow URDF XML to be placed inside the SDF XML:

```
<?xml version="1.0" ?>
<sdf version="1.5">
  <world name="default">
    <model name="pendulum_welded_base">
      [URDF XML for the model]
      <joint name="pendulum_world" type="fixed">
        <child>double_pendulum_with_base::base_link<child>
        <parent>world</parent>
      </joint>
    </model>
  </world>
</sdf>
```

Or, link to a separate URDF XML using `<include>` as so:

```
<?xml version="1.0" ?>
<sdf version="1.5">
  <world name="default">
    <model name="pendulum_welded_base">
      <include>
        <uri>file:///home/user/my_robot.urdf</uri>
      </include>
      <joint name="pendulum_world" type="fixed">
        <child>double_pendulum_with_base::base_link<child>
        <parent>world</parent>
      </joint>
    </model>
  </world>
</sdf>
```

**Comment by tri-ltyyu** [comment] 2019-03-22 18:35
Assigning to @jwnimmer-tri to see if still relevant

**Comment by jwnimmer-tri** [comment] 2019-03-22 21:02
From a quick scan of the code, I think our MultibodyPlant parser still treats "world" specially (it has checks against kWorldName which is `"world"`).  Whether the complaint in this issue description is a relevant defect or not, I'm not sure.  Maybe @sammy-tri can weigh in?

**Comment by sammy-tri** [comment] 2019-03-25 16:30
Yes, we still treat `"world"` in this fashion.  From reading the link to gazebo above, I think it might do the same thing? I'm OK with closing this issue.

**Comment by jwnimmer-tri** [comment] 2019-03-25 16:36
Alright.  I'll chalk this up as "When someone who cares about this and knows their business enough to (re-)articulate what the problem is speaks up, then we can re-open and fix it at that point."

**Closed by jwnimmer-tri** 2019-03-25 16:36 UTC
Labels: priority: medium, team: dynamics, type: bug, type: feature request
