### ISSUE TITLE
py manipulation: Should move `differential_ik` system from `drake/examples` to `pydrake.manipulation`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13548] opened 2020-06-11 20:04 UTC
See Slack / StackOverflow:
https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1591904734050100
https://stackoverflow.com/questions/62332244/access-differentialik-outside-of-drake

Basically, it only exists here:
https://github.com/RobotLocomotion/drake/blob/4ea3c4b434025361f7431171511483754724b9e7/examples/manipulation_station/differential_ik.py

But should exist in `pydrake.manipulation` in some form.

\cc @mpetersen94 @pvarin

**Comment by EricCousineau-TRI** [comment] 2020-06-11 20:05
@mpetersen94 I won't have time in the next few days to do this. Is it something you're OK with waiting for, or might you have time to try moving this?

**Comment by jwnimmer-tri** [comment] 2020-06-12 12:27
The code was added in #9870 by \CC @RussTedrake with a `TODO(russt): Clean this up and move it to C++.`  I am not sure that only changing its module is the correct path forward, especially with Russ' recent mention of porting the manipulation station code to C++.  Maybe a better path forward is moving it to C++ while cleaning it up, testing it, and binding it for pydrake?

**Comment by EricCousineau-TRI** [comment] 2020-06-12 13:29
That's one way to do it, and that's the more ideal. However, if I were to do it, I'd definitely only want to do the minimum amt if possible, esp. given that the request is for the Python interface.

Will mull it over some more, though. Thanks!

**Comment by jwnimmer-tri** [comment] 2020-06-12 13:36
If the need is just to call the code, then _forking_ it the minimum effort possible; it takes like 10 seconds.  To move it into a public library, the PR is anyway going to have to do the "cleanup" (fix the mutable-member-context problem, write tests, decide which methods are public, add API docs).

**Comment by EricCousineau-TRI** [comment] 2020-06-12 13:40
SGTM. @mpetersen94 You cool with forking for now?

**Comment by mpetersen94** [comment] 2020-06-12 14:19
Yes, I can just copy-pasta for now.

**Comment by RussTedrake** [comment] 2020-07-05 11:21
This is a duplicate of #11581.
It's on my shortlist.

**Closed by RussTedrake** 2020-07-05 11:21 UTC
Labels: component: pydrake, priority: low, team: manipulation
