### ISSUE TITLE
BulletModel::findClosestPointsBtwElements warning spew

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1427] opened 2015-10-15 05:32 UTC
While running unit tests in systems/plants/test, I'm getting lots of warnings that look like
```
In BulletModel::findClosestPointsBtwElements: No closest point found between 140644628387088 and 140644628358928
```
Should I be worried? Should the warning be silenced?

**Comment by RussTedrake** [comment] 2015-10-15 10:21
Duplicate of #1378

**Closed by RussTedrake** 2015-10-15 10:21 UTC
