### ISSUE TITLE
[geometry] Scalar conversion of ProximityProperties

### ISSUE THREAD

**Issue by DamrongGuoy** [RobotLocomotion/drake#18195] opened 2022-10-27 15:43 UTC
@amcastro-tri mentioned that ProximityProperties do not allow us to scalar convert to AutoDiffXd. 

At the moment I can neither confirm nor deny.  The doxygen https://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1_proximity_properties.html doesn't mention anything.

**Comment by DamrongGuoy** [comment] 2022-10-27 19:41
I agree that #18188 doesn't need this anymore. I updated the problem description.

**Comment by DamrongGuoy** [comment] 2022-10-27 20:03
To be clear, @amcastro-tri, by scalar conversion, you meant if we construct properties using this function with template parameter ValueType = `double`:
```C++
  template <typename ValueType>
  void AddProperty(const std::string& group_name, const std::string& name,
                   const ValueType& value);
  ProximityProperties properties_double;
  double double_value=0.0;
  properties_double.AddProperty<double>(group, name, double_value);                   
```
Then, later, we might want to change it to AutoDiffXd like this, correct?
```
  ProximityProperties properties_AutoDiffXd = ...convert from properties_double...
  AutoDiffXd autodiff_value = properties_AutoDiffXd.GetProperty<AutoDiffXd>(group, name);
```

**Comment by jwnimmer-tri** [comment] 2024-03-20 01:52
Possibly a duplicate of #5454?  Anyway, not clear what the problem is.

**Closed by jwnimmer-tri** 2024-03-20 01:52 UTC
Labels: type: feature request, priority: low, component: geometry proximity
