### ISSUE TITLE
uninitialized warning on gcc 5.4 -m32 

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#4146] opened 2016-11-17 16:29 UTC
```
In file included from /home/ubuntu/drake/drake/../drake/systems/framework/primitives/gain.h:6:0,
                 from /home/ubuntu/drake/drake/../drake/systems/framework/primitives/gain-inl.h:8,
                 from /home/ubuntu/drake/drake/systems/framework/primitives/test/gain_scalartype_test.cc:1:
/home/ubuntu/drake/drake/../drake/systems/framework/leaf_system.h: In member function ‘void drake::systems::LeafSystem<T>::DoCalcNextUpdateTime(const drake::systems::Context<T>&, drake::systems::UpdateActions<T>*) const [with T = Eigen::AutoDiffScalar<Eigen::Matrix<double, 2, 1, 2> >]’:
/home/ubuntu/drake/drake/../drake/systems/framework/leaf_system.h:264:75: error: ‘*((void*)&<anonymous> +16)’ is used uninitialized in this function [-Werror=uninitialized]
         std::numeric_limits<typename Eigen::NumTraits<T1>::Real>::infinity();
                                                                           ^
/home/ubuntu/drake/drake/../drake/systems/framework/leaf_system.h:264:75: error: ‘*((void*)&<anonymous> +24)’ is used uninitialized in this function [-Werror=uninitialized]
cc1plus: some warnings being treated as errors
```

**Comment by jwnimmer-tri** [comment] 2016-11-18 23:54
What's the recipe to repro?

**Comment by jwnimmer-tri** [comment] 2016-12-12 13:32
@BetsyMcPhail how do we observe or reproduce the error, in order to fix it?

**Comment by BetsyMcPhail** [comment] 2016-12-13 12:15
Thanks for the reminder - I will try to get some more information on this error.

**Comment by david-german-tri** [comment] 2017-04-11 15:19
We were originally interested in standing up a Xenial 32-bit build to replace the Windows 32-bit coverage that we turned down in October 2016.  As of November, I believe this error was the only known blocking issue.

I think it would still be nice to get this coverage, but I'm tagging it as low-priority, since we haven't had any particular demand for 32-bit Drake.

**Comment by EricCousineau-TRI** [comment] 2018-11-02 14:05
For the MATLAB versions that we are testing on for our lightweight `call_matlab` interface, I don't believe 32-bit is an option for compilation anymore. Closing for now.

\cc @jamiesnape

**Closed by EricCousineau-TRI** 2018-11-02 14:05 UTC
Labels: configuration: linux, priority: low, team: kitware, type: continuous integration
