### ISSUE TITLE
Initializing a MultibodyPlant segfaults when time_step=0

### ISSUE THREAD

**Issue by deq2** [RobotLocomotion/drake#13678] opened 2020-07-14 18:32 UTC
I'm trying to use direct collocation with a custom urdf robot. To do this I need to initialize the the MultibodyPlant with time_step=0.0. However, the program fails with a segfault. I've added a code snippit below:
https://gist.github.com/deq2/b39bf8d1f8a1108de000ead2ac90f0f6

(Note I was running with Python version Python 3.6.9 on Ubuntu 16.04)

**Comment by rpoyner-tri** [comment] 2020-07-14 20:57
I've adapted the snippet to live in the drake tree in my branch; seg-fault reproduced. Investigating.

**Comment by sherm1** [comment] 2020-07-14 21:07
Looks like it declares the MultibodyPlant to be continuous but then asks (at the end) for the discrete state variables (which don't exist in that case). I believe if it asked for continuous state variables all would be well.

**Comment by rpoyner-tri** [comment] 2020-07-14 21:08
@sherm1 Agreed. I'm pondering whether the API hazard with discrete state is sufficiently documented.

**Comment by rpoyner-tri** [comment] 2020-07-14 21:13
Ah. The code path that yields the seg-fault runs through a DRAKE_ASSERT that is apparently disarmed in libdrake.so as built. Do we provide an asserts-enabled version of libdrake.so with instructions, to help external users debug this sort of thing?

**Comment by rpoyner-tri** [comment] 2020-07-14 21:15
@deq2 this branch https://github.com/rpoyner-tri/drake/tree/gh13678 has a couple of commits showing the adapted code, and some changes I made to avoid the misuse and print out various bits of context info.

**Comment by sherm1** [comment] 2020-07-14 21:22
> The code path that yields the seg-fault runs through a DRAKE_ASSERT ... Do we provide an asserts-enabled version of libdrake.so ...

That should instead be a nice error message like "You asked for a reference to discrete variables but there aren't any in this model." Minor user misunderstandings shouldn't cause segfaults!

**Comment by rpoyner-tri** [comment] 2020-07-14 21:34
@sherm1 again, agreed. Presumably that's just a change of error handling. I'll look at the options.

**Comment by deq2** [comment] 2020-07-14 21:38
Ah I understand the issue. Thanks for getting back to me so quickly.

**Comment by rpoyner-tri** [comment] 2020-07-14 21:39
@deq2 glad we could help. I'll have a PR up at some point for an improved error message, but that shouldn't hold you up.

**Comment by rpoyner-tri** [comment] 2020-07-14 23:14
https://github.com/robotlocomotion/drake/pull/13681 is one proposal for a fix.

**Comment by rpoyner-tri** [comment] 2020-07-17 17:17
Patch merged.

**Closed by rpoyner-tri** 2020-07-17 17:17 UTC
Labels: team: dynamics
