### ISSUE TITLE
win32 compilation fails on functional_form.h

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#3648] opened 2016-10-03 11:10 UTC
```
(ClCompile target) ->
  Z:\russt\drake-distro-win32\drake\..\drake/common/functional_form.h(685): fatal error C1001: An internal error has occurred in the compiler. [Z:\russt\drake-distro-win32\build\drake\common\test\functional_form_test.vcxproj]
```
My CMakeCache is attached.  
[CMakeCache.txt](https://github.com/RobotLocomotion/drake/files/506060/CMakeCache.txt)

**Comment by RussTedrake** [comment] 2016-10-03 11:17
possibly related
```
  functional_form.cc
Z:\russt\drake-distro-win32\drake/common/functional_form.h(546): warning C4624: 'drake::FunctionalForm::Variable::<unnamed-tag>': destructor was implicitly defined as deleted because a base class destructor is inaccessible or deleted [Z:\russt\drake-distro-win32\build\drake\common\drakeCommon.vcxproj]
 ```

**Comment by bradking** [comment] 2016-10-03 13:58
@RussTedrake what git sha1 do you have checked out?  Which build configuration (Debug, Release, etc.) are you building in VS?

**Comment by RussTedrake** [comment] 2016-10-03 17:43
it happened with the master SHA.  Both Release and Debug modes.  Building from cmake —build at the command line (via VS).

**Comment by bradking** [comment] 2016-10-03 17:57
I've built commit `139d6077` as both `Debug` and `Release` with VS 2015 (x86 arch) and cannot reproduce the ICE.

The next step is to try to compile your exact translation unit.  Please open the project in the VS IDE, expand the `functional_form_test` project, and find the `functional_form_test.cc` source.  Right-click and navigate `Properties -> C/C++ -> Preprocessor -> Preprocess to a File` and choose `Yes (/P)`.  Apply and quit the dialog.  Then right-click again and choose `Compile`.  Finally, navigate again and turn the option back off.  Then in the build tree you should be able to find a `.i` file with the preprocessor output for the translation unit that ICEs.  Please attach that here.

**Comment by RussTedrake** [comment] 2016-10-04 09:50
@bradking — thank you.  but if it’s turning out to be this difficult then I think we should drop this, since we are dropping support for msvc anyhow.  It could be some quirk of my virtual machine (running out of memory handling the templates, etc).

**Comment by bradking** [comment] 2016-10-05 15:51
> I think we should drop this, since we are dropping support for msvc anyhow.

Okay, closing for now then.  We can re-open if needed in the future.

**Closed by bradking** 2016-10-05 15:51 UTC
Labels: configuration: windows, priority: medium, team: kitware, type: installation and distribution
