### ISSUE TITLE
Provide warning when MultibodyPlant.SetDefaultPositions() is set outside position limits 

### ISSUE THREAD

**Issue by yu-fz** [RobotLocomotion/drake#18756] opened 2023-02-08 23:59 UTC
Currently, MultibodyPlant.SetDefaultPositions() will set joint positions directly, without first checking the position limits of the joint. 
This may cause MbPs to initialize in bad states if the user is not careful about selecting initial positions that respect the corresponding limits prescribed by model files or set elsewhere. 

### Suggestion: 
When `SetDefaultPositions()` sets joint positions, check to see if `q` is between `Joint.position_lower_limits()` and `Joint.position_upper_limits()`. Provide a warning message to the user in the event of any position limit violations, including the joint name and the upper and lower limit values in the warning message.

**Comment by amcastro-tri** [comment] 2023-02-15 14:53
I wonder, is a warning message preferable over an exception?

**Comment by sherm1** [comment] 2023-02-15 16:01
Closing as duplicate of #15765 where there is a useful discussion regarding subtleties of this request.

**Closed by sherm1** 2023-02-15 16:01 UTC
Labels: type: feature request, component: multibody plant
