### ISSUE TITLE
docker installation instructions may lead windows users astray

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#13047] opened 2020-04-12 12:28 UTC
Reported [on stack-overflow](https://stackoverflow.com/questions/61168362/drake-problem-first-installation-in-windows).

Our instructions on https://drake.mit.edu/docker.html point people to some out-of-date resources from the MIT classes.  I think we should move any tips for windows users into the drake docs, or somehow produce an issue/forum where we can let the community update our collective knowledge about if / how that works.  (it could even be a github issue, in which case the work would just be to write "windows is unsupported, but please contribute any of your updates/findings as a comment on the issue...").

**Comment by jwnimmer-tri** [comment] 2020-05-14 13:06
Relates #7654 (mostly a duplicate).  The bottom line is that we need to zap the confusing, stale, unsupported, and untested text, one way or another.  We should probably even do that ASAP, even if we don't have replacement text ready yet.

**Comment by jwnimmer-tri** [comment] 2020-05-28 13:27
Calling this a duplicate of #7654, we'll remove the instructions.

**Closed by jwnimmer-tri** 2020-05-28 13:27 UTC
Labels: component: distribution, priority: medium, team: kitware, type: onramp
