### ISSUE TITLE
Implement a set of unit tests for obj readers

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#2782] opened 2016-07-12 13:32 UTC
`DrakeShapes::Mesh` implements reader `LoadObjFile` to load obj files. The reader right now only supports the parsing of vertices and triangle faces, no normals, texture coordinates or any other obj features. 
A set of unit tests is needed to verify the reader properly reports parsing errors when an obj file either does not satisfy the obj specification or the parser does not support a given feature.

**Comment by nkoenig** [comment] 2016-10-06 15:27
This is a duplicate of #3701

**Closed** 2016-10-06 20:08 UTC
Labels: priority: backlog, team: dynamics
