### ISSUE TITLE
Vector output ports with size = 0 have data type set to kAbstractValued

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#10864] opened 2019-03-08 13:06 UTC
# Problem:
In `CreateCachedLeafOutputPort()` we have the following logic for inferring data type from size:
https://github.com/RobotLocomotion/drake/blob/a7700d3592b72a23cd46e75c9841ae3844bffdb4/systems/framework/leaf_system.h#L2498
This makes it impossible to create 0-element vector output ports, which in turn makes it impossible to connect anything to 0-element vector input ports, for which `get_data_type() == kVectorValued`.

# Proposal:
Pass a `data_type` argument into `CreateCachedLeafOutputPort()` rather than attempting to infer it based on size.

**Comment by jwnimmer-tri** [comment] 2019-03-08 14:25
I have a fix for this in progress.

**Comment by EricCousineau-TRI** [comment] 2019-03-08 15:20
https://github.com/RobotLocomotion/drake/issues/10105 is a duplicate of this.

**Comment by jwnimmer-tri** [comment] 2019-03-08 15:48
Would you marked #10105 as closed now (citing this issue), if indeed its a strict duplicate?

**Comment by EricCousineau-TRI** [comment] 2019-03-08 16:00
Done.

**Closed** 2019-03-08 18:49 UTC
Labels: priority: high, team: dynamics
