### ISSUE TITLE
Cannot receive LCM messages on Mac

### ISSUE THREAD

**Issue by patmarion** [RobotLocomotion/drake#416] opened 2014-09-22 13:36 UTC
This issue is responsible for broken message acks between the visualizer and drake.  You can reproduce the issue by running:

cd examples/Pendulum/test
testLCMPlant

On Mac, it prints:

Error using testLCMPlant (line 14)
looks like i'm not receiving LCM dynamics messages

The issue is that the Java LCM receiver thread in LCM.jar does not start when executed in Matlab on Mac.  This could be a Java/Matlab issue, not necessarily an LCM or Drake issue.  I tested on Mac 10.8 and Matlab 2014a.

**Comment by RussTedrake** [comment] 2015-04-21 21:23
closing as duplicate of #317

**Closed by RussTedrake** 2015-04-21 21:23 UTC
