### ISSUE TITLE
pydrake lint: Should add and fix `flake8 --select=F` checks

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#14234] opened 2020-10-21 19:57 UTC
On 6fa365e502, we gots a few:
```
$ find bindings/pydrake -name '*.py' | sort | xargs flake8 --select F bindings/pydrake/**/*.py | grep -v '\*' | wc -l
424
```

Relates ye olde #2465

**Comment by jwnimmer-tri** [comment] 2024-03-21 18:31
Closing as duplicate of #19827.

**Closed by jwnimmer-tri** 2024-03-21 18:31 UTC
Labels: type: cleanup, priority: low, component: pydrake
