### ISSUE TITLE
MultibodyPlant gives a mysterious error if an sdf suddenly gains collision geometry

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10874] opened 2019-03-09 08:42 UTC
Problem:
https://stackoverflow.com/questions/55075161/how-to-debug-inputporteval-required-inputport0-is-not-connected

Proposed solutions:
- update all multibody examples in drake to use the `AddMultibodyPlantSceneGraph` sugar.  
- if possible, provide a better error message for this case.  (not sure if there is a convenient single point of entry for this call, though...)

**Comment by sherm1** [comment] 2019-03-09 21:54
Updating the examples to best practices seems like the right answer.

**Comment by jwnimmer-tri** [comment] 2022-04-26 22:28
I'm resolving this as a duplicate of #11448.

**Closed by jwnimmer-tri** 2022-04-26 22:28 UTC
Labels: type: cleanup, team: dynamics, priority: medium, component: multibody plant, type: usability
