### ISSUE TITLE
Port kinematic trajectory optimization

### ISSUE THREAD

**Issue by tri-ltyyu** [RobotLocomotion/drake#10188] opened 2018-12-11 16:58 UTC
The Drake developers at TRI have an implementation of this algorithm in our internal repositories. In principle, we are happy to share it, but making it public takes time and we have not yet prioritized it. Please upvote it by adding a "thumbs up" reaction to this comment if you want us to know that you are keen.

**Comment by hongkai-dai** [comment] 2019-03-25 16:10
@avalenzue, do you think we will add B-spline approach to Drake?

**Comment by jwnimmer-tri** [comment] 2019-03-25 16:16
\CC @avalenzu

**Comment by avalenzu** [comment] 2019-03-28 13:52
Yes, my current plan is to work on this at the beginning of April.

**Comment by tri-ltyyu** [comment] 2019-04-29 20:33
Just want to see what the status of this is?

**Comment by avalenzu** [comment] 2019-05-01 15:54
This got pushed back due to other work. I'll get back to it after this week.

**Comment by jwnimmer-tri** [comment] 2020-05-07 11:28
Is this a duplicate of #11827?

**Comment by avalenzu** [comment] 2020-05-07 13:38
No. This issue is coming up with new a new trajectory at planning time, whereas #11827 is for smoothing already feasible trajectories, potentially, during execution.

**Comment by jwnimmer-tri** [comment] 2020-05-07 13:40
Ah, so `class KinematicTrajectoryOptimization` in `planning/kinematic_trajectory_optimization.h`?  I'll add it to our tracking sheet.

**Comment by avalenzu** [comment] 2020-05-07 13:42
Correct.

**Comment by jwnimmer-tri** [comment] 2020-12-09 23:09
Relates to #14431.

**Closed** 2022-11-01 01:03 UTC
Labels: type: feature request, type: TRI anzu wishlist, component: planning and control
