### ISSUE TITLE
Rendering MultibodyPlant Tutorial errors out on deepnote

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#16952] opened 2022-04-13 18:36 UTC
Running `rendering_multibody_plant.ipynb` on Deepnote currently causes a kernel failure.

We have to set up a virtual display for rendering to work on deepnote.  E.g. this at the top of the file can resolve the problem:
```
!apt update && apt -y install xvfb
!pip install pyvirtualdisplay
from pyvirtualdisplay import Display
virtual_display = Display(visible=0, size=(1400, 900))
virtual_display.start()
```
(but I assume we will want to add it in a more elegant way)

Moreoever, I think this suggests that our instructions for deploying to deepnote did not involve running this notebook?

**Comment by jwnimmer-tri** [comment] 2022-04-13 18:38
Duplicate of #16866.

**Closed by jwnimmer-tri** 2022-04-13 18:38 UTC
Labels: type: bug, priority: high, team: manipulation
