### ISSUE TITLE
Output visualization data for hydrostatic force model

### ISSUE THREAD

**Issue by tri-ltyyu** [RobotLocomotion/drake#11157] opened 2019-04-04 12:11 UTC
This is a placeholder issue for outputting contact surface, traction, slip velocity, and pressure visualization date, which is needed as Spiral I of Hydroelastic force model implementation

**Comment by edrumwri** [comment] 2019-12-02 15:48
This issue is now effectively a duplicate of #10809. Closing.

**Closed by edrumwri** 2019-12-02 15:48 UTC
Labels: team: dynamics
