### ISSUE TITLE
pack the mex related function into a separate library

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#1087] opened 2015-05-05 18:31 UTC
drakeUtil.h contains a lot of functions that are mex related, such that we cannot construct a standalone C++ test if we want to include drakeUtil.h. Same as QPCommon.h.

**Comment by hongkai-dai** [comment] 2015-05-05 18:31
@RussTedrake , could you assign this to me?

**Comment by psiorx** [comment] 2015-06-11 18:46
This is a duplicate of #1071

**Comment by RussTedrake** [comment] 2015-08-27 02:38
resolved.  we now have drakeMexUtil

**Closed by RussTedrake** 2015-08-27 02:38 UTC
