### ISSUE TITLE
when i try to verify that i have pydrake, i get this error

### ISSUE THREAD

**Issue by noke-cmu** [RobotLocomotion/drake#21643] opened 2024-06-28 20:01 UTC
(drake_env) user_info ~ % python -c 'import pydrake.all; print(pydrake.__file__)'
AttributeError: `itemset` was removed from the ndarray class in NumPy 2.0. Use `arr[index] = value` instead.. Did you mean: 'itemsize'?

The above exception was the direct cause of the following exception:

ImportError: initialization failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user_info/drake_env/lib/python3.12/site-packages/pydrake/all.py", line 43, in <module>
    from .planning import *
ImportError: initialization failed

**Comment by jwnimmer-tri** [comment] 2024-06-28 20:32
Duplicate of https://github.com/RobotLocomotion/drake/issues/21577.

**Closed by jwnimmer-tri** 2024-06-28 20:32 UTC
