### ISSUE TITLE
AutomotiveSimulator Design That Includes PoseAggregator

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5541] opened 2017-03-17 18:31 UTC
This issue tracks the redesign of `AutomotiveSimulator` to support the `PoseAggregator`. It's also a solicitation for feedback comments.

# Current Design
The current design is shown in the image below. Multiple levels of multiplexers are used to stitch together `x_c`, which is then fed into `DrakeVisualizer`.

![current](https://cloud.githubusercontent.com/assets/1388098/24057273/3665b9f8-0b1d-11e7-88a1-df190c20f1bd.jpg)

# Proposed Redesign - Version 3

In this version, the `VisualizationApplicator` is moved to be after `PoseAggregator`. The reason for this is it allows other systems to optionally subscribe to the `PoseBundle` outputted by `PoseAggregator`, which only contains a single pose for each vehicle. Other sensors that need to know the pose of every body in the simulation can subscribe to the `PoseBundle` outputted by `VisualizationApplicator`.

![drake automotivesimulator poseaggregator v3-2](https://cloud.githubusercontent.com/assets/1388098/24115378/8a20af7c-0d79-11e7-90a2-6761ddcf8f6d.png)

# Proposed Redesign - Version 2

In this version, all of the individual car visualization systems are merged into a single `VisualizationApplicator` system.

![drake automotivesimulator poseaggregator v2](https://cloud.githubusercontent.com/assets/1388098/24111804/0525b7d2-0d6e-11e7-99f6-11e500afc3eb.png)

# Proposed Redesign - Version 1

Each vehicle model instance outputs a `PoseVector` and `FrameVelocity` that describes the pose and time-derivative-of-the-pose of its "root" body. For each model instance, its outputs are fed into a `CarVisualizer` that adds the poses of all of the other bodies that collectively represent the visualization of the model instance. It also adds any offsets necessary to ensure the visualization's origin is the same as the model's origin (see #5341). It outputs a `PoseBundle`. All of these `PoseBundle` outputs are then fed into the `PoseAggreagator`, whose output is fed into a `PoseBundleToDrawMessage` system. Note that each `CarVisualizer` system also outputs an `lcmt_viewer_load_robot` message that is then also sent to the visualizer.

![new_v1](https://cloud.githubusercontent.com/assets/1388098/24057359/829e825a-0b1d-11e7-93cc-c9b476c026a7.jpg)

**Comment by david-german-tri** [comment] 2017-03-17 18:57
First pass, two thoughts:

1. Did you consider producing and sending the `lcmt_viewer_load_robot` message outside of the System diagram?  It only needs to be sent once, and everything you need to know to send it is (I think) available before the simulation begins.  Then you can drop the N `LcmPublisherSystem`s.  For an example of this approach, see https://gist.github.com/david-german-tri/0021ef9ff01602e12bf0776b95a7413e

2. I like the `CarVisualization` approach to fixed dependent transforms for now, but it also illustrates the need for a dependent transform primitive in the load-robot message in the future.

**Comment by SeanCurtis-TRI** [comment] 2017-03-17 19:02
@sherm1 and I are operating under the assumption that the system will eventually support an "initialize" phase.  I would hope the `lcmt_viewer_load_robot` messages would be resolved there, explicitly.

**Comment by jwnimmer-tri** [comment] 2017-03-17 19:24
First, this seems like a duplicate of #4112.
Second, David is writing a big reply and I'll wait for that before posting more.

**Comment by david-german-tri** [comment] 2017-03-17 19:25
> @sherm1 and I are operating under the assumption that the system will eventually support an "initialize" phase

I think this would be a misfeature and we should not do it.  (@sherm1 has heard me say so many times before, but @SeanCurtis-TRI may not have.)  The System framework's mission is to express and compose hybrid models.  The dataflow architecture is geared towards answering the question "given this state, what is the next state?" in a form that's safe, transparent, and consistent with the controls literature.

Initialization is not the same problem, or even much a related one.  If there's procedural one-time stuff you need to do before commencing simulation, C++ itself is a great way to express procedural stuff.  The OP is an excellent example.  To make it correct as drawn, yes, you need an initialization phase (or a mutable state hack that simulates an initialization phase).  But it is vastly simpler and cleaner not to think of `load_robot` publication as a Diagram activity at all.

**Comment by SeanCurtis-TRI** [comment] 2017-03-17 19:35
So, it seems to my that `System ⊂ Simulator`.  While I can see the point you make about the purpose of the `System`, simulators benefit from initialization.  And, in fact, it seems that it could rear its head when we actually move from one continuous interval to another (separated by discrete events which modify, or even rebuild the system.)

Furthermore, the mission of the `System` has obviously grown beyond your definition, otherwise there would be no room for `Publish`.

Moral of the story, I'm open to arguments for and against `Initialization`.  I just don't think it's a foregone conclusion.

**Comment by jwnimmer-tri** [comment] 2017-03-17 20:03
It's possible that `CarVisualization` be a bus-to-bus system (for all cars) rather that just one car would scale better in code complexity and runtime complexity.  Especially when we add world geometry into the mix, such as the maliput meshes or flat planes.  Liang, we can chat live on this when you have time.

**Comment by liangfok** [comment] 2017-03-17 20:15
Thanks for all of the feedback! Let me ponder this some more over the weekend. Perhaps we can discuss F2F early next week.

**Closed** 2017-03-30 17:06 UTC
Labels: priority: high, team: cars, type: design, type: question
