### ISSUE TITLE
Deprecation warning in custom_test.py

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9990] opened 2018-11-10 16:07 UTC
```
....../bindings/pydrake/systems/test/custom_test.py:416: DrakeDeprecationWarning: `DeclareAbstractInputPort(self, name)` is deprecated. Please use `(self, name, model_value)` instead.
```

**Comment by RussTedrake** [comment] 2018-11-10 16:08
i wouldn't have seen it if I hadn't run that test with bazel run, i think.  perhaps these need to be louder?

**Comment by jwnimmer-tri** [comment] 2018-11-10 16:09
This is likely a duplicate of #9901.

**Comment by jwnimmer-tri** [comment] 2018-11-10 16:37
I was the one who introduced the test case that cluttered the console output, so I'll take over the issue from @EricCousineau-TRI.

**Closed** 2018-11-11 18:09 UTC
Labels: priority: medium, team: manipulation, type: cleanup
