### ISSUE TITLE
add support for IPOPT in optimization problem

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#316] opened 2014-08-19 17:31 UTC
Currently Ipopt with Mumps solver is slower than SNOPT and fmincon on small size problems. Should add test of Ipopt for problems with different sizes. Add try different linear solvers for Ipopt.

**Comment by RussTedrake** [comment] 2016-04-30 20:19
we need to decide if we will add support for IPOPT in the c++ optimization stack or not.  @hongkai-dai thinks that it is a better alternative than nlopt in terms of performance (but has the downside that it did not have support for windows last time we checked)

**Comment by RussTedrake** [comment] 2016-04-30 20:20
(currently we have limited ipopt support in the matlab optimization classes only)

**Comment by sherm1** [comment] 2016-05-01 00:22
> IPOPT ... did not have support for windows last time we checked

We didn't have any trouble including IPOPT in Simbody for all platforms, including Windows.

**Comment by hongkai-dai** [comment] 2016-05-01 00:25
@sherm1 , did you need to use cygwin or MinGW to compile IPOPT on Windows? I have not found how to install ipopt on Windows without Cygwin or MinGW, according to this page http://www.coin-or.org/Ipopt/documentation/node15.html

**Comment by sherm1** [comment] 2016-05-01 01:16
No, we build it in Visual Studio along with the everything else. 
@chrisdembia, I know you ported a newer version of IpOpt to Simbody recently -- were you able to build it on Windows?

**Comment by chrisdembia** [comment] 2016-05-01 05:00
> @chrisdembia, I know you ported a newer version of IpOpt to Simbody recently -- were you able to build it on Windows?

You are correct; I did not try building that newer version of IpOpt on Windows. It seems like the issue is that IpOpt does not use CMake? [This website](https://projects.coin-or.org/MSVisualStudio) says COIN-OR provides Visual Studio solution files for a number of its projects, but not for IpOpt.

Some other notes about IpOpt:
- Anil Rao at University of Florida (GPOPS-II) has said that there is no clear winner between IpOpt and SNOPT with GPOPS-II (that it depends on the problem).
- IpOpt support for MATLAB seems to be dwindling, particularly for newer versions of MATLAB where something about the mex process has changed. This doesn't matter much if you use IpOpt through C++ and provide your own interface/wrapper for MATLAB.

**Comment by sherm1** [comment] 2016-05-01 05:12
The version of IpOpt that ships with Simbody does build with CMake. We must have added that at some point. @chrisdembia, did you build IpOpt separately with its own build system then and just link with it?

**Comment by chrisdembia** [comment] 2016-05-01 05:24
> The version of IpOpt that ships with Simbody does build with CMake. We must have added that at some point.

Yeah I think Simbody globs up the IpOpt sources with its own CMakeLists.txt.

> @chrisdembia, did you build IpOpt separately with its own build system then and just link with it?

I haven't built or used IpOpt on Windows (aside from within Simbody).

I just checked to see if IpOpt has a Chocolatey package, and it does not. The conda package manager (used mostly for python packages) does have IpOpt binaries (https://anaconda.org/cachemeorg/ipopt_bin).

**Comment by chrisdembia** [comment] 2016-05-01 05:25
Just found a link to IpOpt's mailing list from 2014 with CMakeLists files that someone created for Ipopt.

- http://list.coin-or.org/pipermail/ipopt/2014-April/003687.html
- https://github.com/ampl/coin/blob/master/CMakeLists.txt

**Comment by sherm1** [comment] 2016-05-01 18:45
Awesome -- thanks, Chris!

**Comment by hongkai-dai** [comment] 2016-05-01 21:20
@chrisdembia @sherm1, that is great! Thanks a lot!

**Comment by ggould-tri** [comment] 2016-05-25 19:40
Assigning to sammy as he is already working this problem.

**Comment by sammy-tri** [comment] 2016-08-11 17:01
Marking as closed.  Remaining work is being tracked in #2578 and #2569

**Closed by sammy-tri** 2016-08-11 17:01 UTC
Labels: priority: low, team: manipulation, type: cleanup, type: feature request
