### ISSUE TITLE
MacOS docutils version mismatch

### ISSUE THREAD

**Issue by mposa** [RobotLocomotion/drake#12747] opened 2020-02-18 17:42 UTC
A few students here at Penn have run into this issue on MacOS Catalina. During the prereq installation, pip3 installation of `botocore` fails because it requires `docutils < .16`, whereas these students have all had version .16 installed. Manually downgrading docutils resolved the issue.

**Comment by jamiesnape** [comment] 2020-02-18 18:08
Our scripts will install whatever `botocore` needs (we don't have a dependency on `docutils`). We cannot cover every potential pre-existing configuration, unfortunately.

**Comment by jamiesnape** [comment] 2020-02-18 18:11
Relates https://github.com/boto/botocore/issues/900 https://github.com/boto/botocore/issues/1789, https://github.com/boto/botocore/issues/1796, and maybe a few others.

**Comment by mposa** [comment] 2020-02-18 18:28
From my experience this week, this extends beyond "every potential pre-existing configuration," as 4 of 4 Mac users this week have this issue.

**Comment by jamiesnape** [comment] 2020-02-18 18:29
On a given day it will be different. We cannot legislate for `botocore`. You can complain about the pin to them. If we pin artificially, then we shift the problem too.

**Comment by jamiesnape** [comment] 2020-02-18 18:37
Also I need to know the common package (if any) that is installing docutils that they all have to even have a chance of lessening the impact. Try `pipdeptree` or similar.

**Comment by blandry** [comment] 2020-02-18 22:00
For what it's worth I also ran into this. Like Michael got around it easily but suspect this will unfortunately come up a few time among your users.

**Comment by prometheanfire** [comment] 2020-02-21 04:29
this is not a mac issue, it's a they should only cap when future versions are KNOWN to break only.  Having this happen every few weeks (to this and other libs) is getting old.

pkg_resources.ContextualVersionConflict: (docutils 0.16 (/home/zuul/src/opendev.org/openstack/requirements/.tox/py36-check-uc/lib/python3.6/site-packages), Requirement.parse('docutils<0.16,>=0.10'), {'botocore'})

**Comment by prometheanfire** [comment] 2020-02-21 04:32
See https://github.com/boto/botocore/issues/1872#issuecomment-550500977 as well, I think this is fairly universally looked down upon as a practice.

**Comment by prometheanfire** [comment] 2020-02-21 04:37
if you need to cap docs, use a requirements file for docs jobs that's separate from a normal install.  See https://github.com/openstack/nova/blob/master/doc/requirements.txt for example

**Comment by jwnimmer-tri** [comment] 2020-02-24 15:25
I agree with @jamiesnape that the right answer is to complain to botocore maintainers, and there is not much (if anything) we can do to work around the problem.

The only worthwhile change might be to split drake's dependencies from only "binary" vs "source" to "binary" vs "user source" vs "developer source" where any dependencies not used by tests in the default configuration are deferred to "developer source".  That would be things like clang, valgrind, boto, etc.  That would require add complexity CI, but would _substantially_ reduce the build-from-source dependency footprint.

It would also happen to sidestep the botocore problem, because the default test suite does not use boto for anything AFAICT.

**Comment by RussTedrake** [comment] 2020-03-07 22:02
fwiw -- today i saw this error scroll by during a fresh install on a clean mac machine, but it did not prevent `install_prereqs` from completing.   I was able to `bazel test //...` and also `install`, and saw no problems.

**Comment by jwnimmer-tri** [comment] 2020-05-15 02:57
> ... The only worthwhile change might be to split drake's dependencies from only "binary" vs "source" to "binary" vs "user source" vs "developer source" where any dependencies not used by tests in the default configuration are deferred to "developer source" ...

That's basically what #13168 is proposing for other reasons, so I'll resolve this as a duplicate of that.

**Closed by jwnimmer-tri** 2020-05-15 02:57 UTC
Labels: component: distribution, priority: medium, team: kitware

**Comment by jwnimmer-tri** [comment] 2020-12-17 00:19
Also, as of https://github.com/boto/botocore/issues/900 (botocore 1.18), the docutils dependency is gone.

**Comment by jamiesnape** [comment] 2020-12-17 00:23
Not this precise issue, but they still have their bad habit of pinning dependencies fairly tightly. Still on my troublesome list of modules.
