### ISSUE TITLE
LCM is sometimes unexpectedly absent

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2338] opened 2016-05-13 13:14 UTC
```
In file included from /Users/yosemite/workspace/mac-clang-continuous-matlab/drake/systems/plants/RigidBodyTree.cpp:1:
In file included from /Users/yosemite/workspace/mac-clang-continuous-matlab/drake/../drake/systems/plants/RigidBodyTree.h:15:
/Users/yosemite/workspace/mac-clang-continuous-matlab/drake/../drake/systems/plants/RigidBodyFrame.h:5:10: fatal error: 'drake/drakeRBSystem_export.h' file not found
#include "drake/drakeRBSystem_export.h"
         ^
1 error generated.
```

```
In file included from /Users/yosemite/workspace/mac-clang-continuous-matlab/drake/systems/plants/RigidBodyTreeURDF.cpp:7:
In file included from /Users/yosemite/workspace/mac-clang-continuous-matlab/drake/../drake/systems/plants/rigid_body_tree_urdf.h:7:
/Users/yosemite/workspace/mac-clang-continuous-matlab/drake/../drake/systems/plants/RigidBodyFrame.h:5:10: fatal error: 'drake/drakeRBSystem_export.h' file not found
#include "drake/drakeRBSystem_export.h"
         ^
1 error generated.
```

https://drake-cdash.csail.mit.edu/viewBuildError.php?onlydeltap&buildid=19459

**Comment by avalenzu** [comment] 2016-05-14 02:16
I'm seeing this on an OSX Yosemite machine as well.

**Comment by avalenzu** [comment] 2016-05-15 17:38
To follow up, on my machine this was caused by #2357

**Comment by david-german-tri** [comment] 2016-05-25 15:45
#2357 resolves this opaque build failure, but does not address why LCM is sometimes absent.

**Comment by liangfok** [comment] 2016-05-25 16:03
I believe this is a duplicate of https://github.com/RobotLocomotion/drake/issues/2341.

**Comment by david-german-tri** [comment] 2016-05-25 17:01
Great, thanks!  Closing this one.

**Closed by david-german-tri** 2016-05-25 17:01 UTC
Labels: priority: high, team: build cop, team: software core, type: build
