### ISSUE TITLE
Remove All Instances of "using namespace".

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3495] opened 2016-09-18 04:42 UTC
# Motivation

It is against the style guide: https://google.github.io/styleguide/cppguide.html#Namespaces

# TODO

Update the following files:

```
$ cd drake-distro/drake

$ find . -type f -name "*.h" -print | xargs grep "using namespace"
./examples/Acrobot/Acrobot.h:using namespace std;
./examples/Pendulum/Pendulum.h:using namespace std;
./examples/QPInverseDynamicsForHumanoids/humanoid_status.h:using namespace Eigen;
./examples/QPInverseDynamicsForHumanoids/rigid_body_tree_utils.h:using namespace Eigen;
./examples/Quadrotor/Quadrotor.h:    using namespace std;
./examples/Quadrotor/Quadrotor.h:    using namespace std;
./math/expmap.h:  using namespace std;
./math/expmap.h:  using namespace std;  // required for ADL of floor() and round().
./systems/plants/RigidBodySystem.h:    using namespace Eigen;
./util/drakeGeometryUtil.h:  using namespace std;
./util/drakeGeometryUtil.h:  using namespace std;
./util/drakeGeometryUtil.h:  using namespace std;
./util/drakeGeometryUtil.h:  using namespace Eigen;
./util/drakeGeometryUtil.h:  using namespace Eigen;
./util/drakeGeometryUtil.h:  using namespace Eigen;
./util/drakeGeometryUtil.h:  using namespace Eigen;
./util/drakeMexUtil.h:  using namespace Eigen;
./util/drakeMexUtil.h:  using namespace std;
./util/drakeUtil.h:  using namespace std;
./util/drakeUtil.h:  using namespace Eigen;
./util/standardMexConversions.h:  using namespace Eigen;
./util/standardMexConversions.h:  using namespace std;
./util/standardMexConversions.h:  using namespace Eigen;

$ find . -type f -name "*.cc" -print | xargs grep "using namespace"
./common/polynomial.cc:using namespace std;
./common/polynomial.cc:using namespace Eigen;
./common/test/trig_poly_test.cc:using namespace Eigen;
./common/test/trig_poly_test.cc:using namespace std;
./examples/Pendulum/pendulum_run_dynamics.cc:using namespace std;
./examples/Pendulum/pendulum_run_dynamics.cc:using namespace drake;
./examples/Pendulum/pendulum_run_energy_shaping.cc:using namespace std;
./examples/Pendulum/pendulum_run_energy_shaping.cc:using namespace drake;
./examples/Pendulum/pendulum_run_lqr.cc:using namespace std;
./examples/Pendulum/pendulum_run_lqr.cc:using namespace drake;
./examples/QPInverseDynamicsForHumanoids/qp_controller.cc:using namespace drake::solvers;
./math/random_rotation.cc:using namespace Eigen;
./math/test/cross_product_test.cc:using namespace Eigen;
./solvers/qp.cc:using namespace Eigen;
./solvers/qp.cc:using namespace std;

$ find . -type f -name "*.cpp" -print | xargs grep "using namespace"
./examples/@VanDerPolCpp/dynamicsRHS.cpp:using namespace Eigen;
./examples/@VanDerPolCpp/dynamicsRHS.cpp:using namespace std;
./examples/Acrobot/@AcrobotPlantCpp/manipulatorDynamics.cpp:using namespace Eigen;
./examples/Acrobot/@AcrobotPlantCpp/manipulatorDynamics.cpp:using namespace std;
./examples/Atlas/atlasUtil.cpp:using namespace Eigen;
./examples/Quadrotor/runDynamics.cpp:using namespace std;
./examples/Quadrotor/runDynamics.cpp:using namespace drake;
./examples/Quadrotor/runDynamics.cpp:using namespace Eigen;
./examples/Quadrotor/runLQR.cpp:using namespace std;
./examples/Quadrotor/runLQR.cpp:using namespace Eigen;
./examples/Quadrotor/runLQR.cpp:using namespace drake;
./matlab/solvers/fastQPmex.cpp:using namespace Eigen;
./matlab/solvers/fastQPmex.cpp:using namespace std;
./matlab/solvers/gurobiQPmex.cpp:using namespace Eigen;
./matlab/solvers/gurobiQPmex.cpp:using namespace std;
./matlab/solvers/lqrmex.cpp:using namespace Eigen;
./matlab/solvers/NonlinearProgramSnoptmex.cpp:using namespace std;
./matlab/solvers/qpSpline/nWaypointCubicSplineFreeKnotTimesmex.cpp:using namespace std;
./matlab/solvers/qpSpline/nWaypointCubicSplineFreeKnotTimesmex.cpp:using namespace Eigen;
./matlab/solvers/qpSpline/nWaypointCubicSplinemex.cpp:using namespace std;
./matlab/solvers/qpSpline/nWaypointCubicSplinemex.cpp:using namespace Eigen;
./solvers/qpSpline/splineGeneration.cpp:using namespace std;
./solvers/qpSpline/splineGeneration.cpp:using namespace Eigen;
./solvers/qpSpline/SplineInformation.cpp:using namespace std;
./systems/controllers/constructQPDataPointerMex.cpp:using namespace Eigen;
./systems/controllers/controlUtil.cpp:using namespace Eigen;
./systems/controllers/InstantaneousQPController.cpp:using namespace Eigen;
./systems/controllers/instantaneousQPControllermex.cpp:using namespace std;
./systems/controllers/instantaneousQPControllermex.cpp:using namespace Eigen;
./systems/controllers/supportDetectmex.cpp:using namespace std;
./systems/controllers/supportDetectmex.cpp:using namespace Eigen;
./systems/controllers/zmpUtil.cpp:using namespace Eigen;
./systems/controllers/zmpUtil.cpp:using namespace std;
./systems/LCMSystem.cpp:using namespace drake;
./systems/plants/allCollisionsmex.cpp:using namespace Eigen;
./systems/plants/allCollisionsmex.cpp:using namespace std;
./systems/plants/approximateIK.cpp:using namespace std;
./systems/plants/approximateIK.cpp:using namespace Eigen;
./systems/plants/approximateIKEIQPmex.cpp:using namespace std;
./systems/plants/approximateIKEIQPmex.cpp:using namespace std;
./systems/plants/approximateIKmex.cpp:using namespace std;
./systems/plants/approximateIKmex.cpp:using namespace Eigen;
./systems/plants/collidingPointsCheckOnlymex.cpp:using namespace Eigen;
./systems/plants/collidingPointsCheckOnlymex.cpp:using namespace std;
./systems/plants/collidingPointsmex.cpp:using namespace Eigen;
./systems/plants/collidingPointsmex.cpp:using namespace std;
./systems/plants/collision/DrakeCollision.cpp:using namespace std;
./systems/plants/collision/DrakeCollision.cpp:using namespace Eigen;
./systems/plants/collision/Element.cpp:using namespace Eigen;
./systems/plants/collision/Element.cpp:using namespace std;
./systems/plants/collision/Model.cpp:using namespace std;
./systems/plants/collision/Model.cpp:using namespace Eigen;
./systems/plants/collisionDetectFromPointsmex.cpp:using namespace Eigen;
./systems/plants/collisionDetectFromPointsmex.cpp:using namespace std;
./systems/plants/collisionDetectmex.cpp:using namespace Eigen;
./systems/plants/collisionDetectmex.cpp:using namespace std;
./systems/plants/collisionRaycastmex.cpp:using namespace Eigen;
./systems/plants/collisionRaycastmex.cpp:using namespace std;
./systems/plants/computeS1Trajmex.cpp:using namespace Eigen;
./systems/plants/computeS1Trajmex.cpp:using namespace std;
./systems/plants/constraint/constraintCategorymex.cpp:using namespace Eigen;
./systems/plants/constraint/constraintCategorymex.cpp:using namespace std;
./systems/plants/constraint/constraintTypemex.cpp:using namespace Eigen;
./systems/plants/constraint/constraintTypemex.cpp:using namespace std;
./systems/plants/constraint/constructPtrRigidBodyConstraint.cpp:using namespace std;
./systems/plants/constraint/constructPtrRigidBodyConstraint.cpp:using namespace Eigen;
./systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp:using namespace Eigen;
./systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp:using namespace std;
./systems/plants/constraint/RigidBodyConstraint.cpp:using namespace Eigen;
./systems/plants/constraint/RigidBodyConstraint.cpp:  using namespace std;
./systems/plants/constraint/RigidBodyConstraint.cpp:  using namespace drake;
./systems/plants/constraint/test/testConstraintConstructor.cpp:using namespace std;
./systems/plants/constraint/testQuasiStaticConstraintmex.cpp:using namespace Eigen;
./systems/plants/constraint/testQuasiStaticConstraintmex.cpp:using namespace std;
./systems/plants/constraint/testSingleTimeLinearPostureConstraintmex.cpp:using namespace std;
./systems/plants/constraint/testSingleTimeLinearPostureConstraintmex.cpp:using namespace Eigen;
./systems/plants/constraint/updatePtrRigidBodyConstraintmex.cpp:using namespace Eigen;
./systems/plants/constraint/updatePtrRigidBodyConstraintmex.cpp:using namespace std;
./systems/plants/constructModelmex.cpp:using namespace Eigen;
./systems/plants/constructModelmex.cpp:using namespace std;
./systems/plants/contactConstraintsmex.cpp:using namespace std;
./systems/plants/contactConstraintsmex.cpp:using namespace Eigen;
./systems/plants/contactConstraintsmex.cpp:using namespace drake;
./systems/plants/createKinematicsCacheAutoDiffmex.cpp:using namespace Eigen;
./systems/plants/createKinematicsCacheAutoDiffmex.cpp:using namespace std;
./systems/plants/createKinematicsCachemex.cpp:using namespace Eigen;
./systems/plants/createKinematicsCachemex.cpp:using namespace std;
./systems/plants/IKoptions.cpp:using namespace std;
./systems/plants/IKoptions.cpp:using namespace Eigen;
./systems/plants/IKoptionsmex.cpp:using namespace std;
./systems/plants/IKoptionsmex.cpp:using namespace Eigen;
./systems/plants/inverseKinmex.cpp:using namespace std;
./systems/plants/inverseKinmex.cpp:using namespace Eigen;
./systems/plants/inverseKinPointwisemex.cpp:using namespace std;
./systems/plants/inverseKinPointwisemex.cpp:using namespace Eigen;
./systems/plants/inverseKinTrajmex.cpp:using namespace std;
./systems/plants/inverseKinTrajmex.cpp:using namespace Eigen;
./systems/plants/jointLimitConstraintsmex.cpp:using namespace Eigen;
./systems/plants/jointLimitConstraintsmex.cpp:using namespace std;
./systems/plants/joints/DrakeJoint.cpp:using namespace Eigen;
./systems/plants/joints/HelicalJoint.cpp:using namespace Eigen;
./systems/plants/joints/PrismaticJoint.cpp:using namespace Eigen;
./systems/plants/joints/QuaternionFloatingJoint.cpp:using namespace Eigen;
./systems/plants/joints/QuaternionFloatingJoint.cpp:using namespace std;
./systems/plants/joints/RevoluteJoint.cpp:using namespace Eigen;
./systems/plants/joints/test/testDrakeJointsmex.cpp:using namespace Eigen;
./systems/plants/joints/test/testDrakeJointsmex.cpp:using namespace std;
./systems/plants/positionConstraintsmex.cpp:using namespace Eigen;
./systems/plants/positionConstraintsmex.cpp:using namespace std;
./systems/plants/RigidBodySystem.cpp:  using namespace std;
./systems/plants/RigidBodySystem.cpp:  using namespace Eigen;
./systems/plants/RigidBodyTree.cpp:using namespace Eigen;
./systems/plants/RigidBodyTreeContact.cpp:using namespace Eigen;
./systems/plants/RigidBodyTreeContact.cpp:using namespace std;
./systems/plants/rigidBodyTreeMexFunctions.cpp:using namespace std;
./systems/plants/rigidBodyTreeMexFunctions.cpp:using namespace Eigen;
./systems/plants/rigidBodyTreeMexFunctions.cpp:using namespace drake;
./systems/plants/shapes/Element.cpp:using namespace Eigen;
./systems/plants/smoothDistancePenaltymex.cpp:using namespace Eigen;
./systems/plants/smoothDistancePenaltymex.cpp:using namespace std;
./systems/plants/solveLCPmex.cpp:using namespace Eigen;
./systems/plants/solveLCPmex.cpp:using namespace std;
./systems/plants/surfaceTangentsmex.cpp:using namespace Eigen;
./systems/plants/surfaceTangentsmex.cpp:using namespace std;
./systems/plants/test/benchmarkRigidBodyTree.cpp:using namespace std;
./systems/plants/test/benchmarkRigidBodyTree.cpp:using namespace Eigen;
./systems/plants/test/compareParsersmex.cpp:using namespace Eigen;
./systems/plants/test/compareParsersmex.cpp:using namespace std;
./systems/plants/test/debugManipulatorDynamics.cpp:using namespace std;
./systems/plants/test/testApproximateIK.cpp:using namespace std;
./systems/plants/test/testApproximateIK.cpp:using namespace Eigen;
./systems/plants/test/testIKoptionsmex.cpp:using namespace std;
./systems/plants/test/testIKoptionsmex.cpp:using namespace Eigen;
./systems/plants/test/testKinematicsCacheChecks.cpp:using namespace std;
./systems/plants/test/testKinematicsCacheChecks.cpp:using namespace Eigen;
./systems/plants/test/urdfCollisionTest.cpp:using namespace std;
./systems/plants/test/urdfKinTest.cpp:using namespace std;
./systems/plants/test/urdfManipulatorDynamicsTest.cpp:using namespace std;
./systems/plants/test/urdfManipulatorDynamicsTest.cpp:using namespace Eigen;
./systems/plants/testFrameParsermex.cpp:using namespace std;
./systems/plants/xmlUtil.cpp:using namespace std;
./systems/plants/xmlUtil.cpp:using namespace Eigen;
./systems/plants/xmlUtil.cpp:using namespace tinyxml2;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/duration.cpp:using namespace std;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/duration.cpp:using namespace Eigen;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/getLastQPInput.cpp:using namespace std;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/getLastQPInput.cpp:using namespace Eigen;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/getQPControllerInput.cpp:using namespace std;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/getQPControllerInput.cpp:using namespace Eigen;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/isFinished.cpp:using namespace std;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/isFinished.cpp:using namespace Eigen;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/private/setDuration.cpp:using namespace std;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/private/setDuration.cpp:using namespace Eigen;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/setStartTime.cpp:using namespace std;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/setStartTime.cpp:using namespace Eigen;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/start_time.cpp:using namespace std;
./systems/robotInterfaces/@QPLocomotionPlanCPPWrapper/start_time.cpp:using namespace Eigen;
./systems/robotInterfaces/constructQPLocomotionPlanmex.cpp:using namespace std;
./systems/robotInterfaces/constructQPLocomotionPlanmex.cpp:using namespace Eigen;
./systems/robotInterfaces/footstepCollocationConstraintsMex.cpp:using namespace std;
./systems/robotInterfaces/octomapWrapper.cpp:using namespace std;
./systems/robotInterfaces/octomapWrapper.cpp:using namespace octomap;
./systems/robotInterfaces/QPLocomotionPlan.cpp:using namespace std;
./systems/robotInterfaces/QPLocomotionPlan.cpp:using namespace Eigen;
./systems/robotInterfaces/QPLocomotionPlan.cpp:using namespace drake;
./systems/test/testAffineSystem.cpp:using namespace std;
./systems/test/testAffineSystem.cpp:using namespace Eigen;
./systems/trajectories/ExponentialPlusPiecewisePolynomial.cpp:using namespace Eigen;
./systems/trajectories/ExpPlusPPTrajectoryEvalmex.cpp:using namespace Eigen;
./systems/trajectories/ExpPlusPPTrajectoryEvalmex.cpp:using namespace std;
./systems/trajectories/isCollisionFree_mex.cpp:using namespace std;
./systems/trajectories/PiecewiseFunction.cpp:using namespace std;
./systems/trajectories/PiecewisePolynomial.cpp:using namespace std;
./systems/trajectories/PiecewisePolynomial.cpp:using namespace Eigen;
./systems/trajectories/PPTmex.cpp:using namespace Eigen;
./systems/trajectories/PPTmex.cpp:using namespace std;
./systems/trajectories/ptToPolyBullet_mex.cpp:using namespace std;
./systems/trajectories/replanFunnels_mex.cpp:using namespace std;
./systems/trajectories/shiftFunnel_snopt_mex.cpp:using namespace std;
./systems/trajectories/test/testExponentialPlusPiecewisePolynomial.cpp:using namespace std;
./systems/trajectories/test/testExponentialPlusPiecewisePolynomial.cpp:using namespace Eigen;
./util/cartesian2cylindricalmex.cpp:using namespace Eigen;
./util/cartesian2cylindricalmex.cpp:using namespace std;
./util/closestExpmapmex.cpp:using namespace std;
./util/closestExpmapmex.cpp:using namespace Eigen;
./util/closestExpmapmex.cpp:using namespace drake;
./util/convexHull.cpp:using namespace std;
./util/convexHull.cpp:using namespace Eigen;
./util/cylindrical2cartesianmex.cpp:using namespace Eigen;
./util/cylindrical2cartesianmex.cpp:using namespace std;
./util/drakeDebugMex.cpp:using namespace std;
./util/drakeGeometryUtil.cpp:using namespace Eigen;
./util/drakeMexUtil.cpp:using namespace std;
./util/drakeMexUtil.cpp:using namespace Eigen;
./util/drakeMexUtil.cpp:  using namespace Eigen;
./util/drakeUtil.cpp:using namespace std;
./util/drakeUtil.cpp:using namespace Eigen;
./util/drakeUtil.cpp:  using namespace Eigen;
./util/expmap2quatImplmex.cpp:using namespace std;
./util/expmap2quatImplmex.cpp:using namespace Eigen;
./util/expmap2quatImplmex.cpp:using namespace drake;
./util/flipExpmapmex.cpp:using namespace std;
./util/flipExpmapmex.cpp:using namespace Eigen;
./util/flipExpmapmex.cpp:using namespace drake;
./util/lcmLogger.cpp:using namespace std;
./util/lcmUtil.cpp:using namespace Eigen;
./util/quat2expmapmex.cpp:using namespace std;
./util/quat2expmapmex.cpp:using namespace Eigen;
./util/quat2expmapmex.cpp:using namespace drake;
./util/quat2expmapSequencemex.cpp:using namespace std;
./util/quat2expmapSequencemex.cpp:using namespace Eigen;
./util/resolveCenterOfPressuremex.cpp:using namespace std;
./util/resolveCenterOfPressuremex.cpp:using namespace Eigen;
./util/test/testConvexHull.cpp:using namespace Eigen;
./util/test/testDrakeGradientUtil.cpp:using namespace Eigen;
./util/test/testGeometryConversionFunctionsmex.cpp:using namespace Eigen;
./util/test/testLCMUtil.cpp:using namespace std;
./util/test/testLCMUtil.cpp:using namespace Eigen;
./util/test/testQuatmex.cpp:using namespace Eigen;
./util/test/testQuatmex.cpp:using namespace std;
./util/test/testQuatmex.cpp:using namespace drake;
./util/unwrapExpmapmex.cpp:using namespace std;
./util/unwrapExpmapmex.cpp:using namespace Eigen;
./util/unwrapExpmapmex.cpp:using namespace drake;
./util/yaml/yamlUtil.cpp:using namespace std;
```

**Comment by jwnimmer-tri** [comment] 2016-09-18 11:37
Duplicate of #2271.

**Closed by jwnimmer-tri** 2016-09-18 11:37 UTC
Labels: type: onramp
