### ISSUE TITLE
Windows builds spuriously red due to HTTP 500

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2791] opened 2016-07-12 19:05 UTC
All experimental builds have been affected since sometime this afternoon.

Example: https://drake-jenkins.csail.mit.edu/job/experimental/2629/compiler=msvc-ninja-32,label=windows/console

**Comment by jamiesnape** [comment] 2016-07-12 19:15
Seems to be an issue with communicating with the CDash server.

**Comment by jamiesnape** [comment] 2016-07-13 14:15
Related to #2342. CTest is not respecting the return values that are explicitly set in the script.

**Comment by jamiesnape** [comment] 2016-07-15 14:30
Duplicate of #2817.

**Closed** 2016-07-15 14:31 UTC
Labels: priority: high, team: kitware
