### ISSUE TITLE
[website] Doxygen modules / namespaces need consistent high-level overview

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#12673] opened 2020-02-03 19:40 UTC
I'm writing this motivated in terms of cross-referencing Python modules with C++ modules (#12655), based on these pain points:

> Some initial notes when attempting #12670:
> 
> * Trying to refer to a top-level Doxygen API page is inconsistent. Some components / modules have good module pages, others... not so much. Also, namespace division is also inconsistent, and namespaces do not have general overview.
> * Referring to directories may be the better approach; however: (a) our current Doxygen generation does not produce an overview of classes / functions / modules at the directory level, only at the file level, and (b) the links for directories are based on what looks like a hash that I'm guessing is from an index (and thus hard to generate independently, i.e. only via Sphinx).
> 
> \cc @sherm1 along the topic of C++ doc organization

Regard the approach to address this problem, I don't have a super concrete proposal yet. I would, however, recommend we discuss this in a Google doc, and then refer to the findings here. (I don't have time today to work on that, but could if someone else doesn't get to it soon.)

\cc @RussTedrake

**Comment by jwnimmer-tri** [comment] 2024-03-20 00:39
Closing as duplicate of #12655.  Whatever Doxygen improvements we need to make pydrake docs better, we should just do that.  We don't need a separate tracking issue to track it.

**Closed by jwnimmer-tri** 2024-03-20 00:39 UTC
Labels: type: documentation, priority: medium, component: tutorials
