### ISSUE TITLE
Meshcat does not support capsule geometry

### ISSUE THREAD

**Issue by JoseBarreiros-TRI** [RobotLocomotion/drake#17149] opened 2022-05-10 17:52 UTC
Meshcat trows a warning and fails to render when visualizing a simple capsule defined in a sdf file. 
E.g. `bazel run //manipulation/util:show_model ~/anzu/models/ruxid/cylinders.sdf -- --meshcat default`
warning:
`home/josebarreiros/.cache/bazel/_bazel_josebarreiros/90f3e8e4e37bf5312f47e87299f7a9c9/execroot/drake/bazel-out/k8-opt/bin/manipulation/util/show_model.runfiles/drake/bindings/pydrake/systems/meshcat_visualizer.py:550: UserWarning: Unsupported shape <pydrake.geometry.Capsule object at 0x7fb3ba26d4f0> ignored
  warnings.warn(f"Unsupported shape {shape} ignored")`

**Comment by jwnimmer-tri** [comment] 2022-05-10 18:09
That's a message from the old, deprecated visualizer (see #16978).  Unless you have an example from the current code, we should close this as "won't fix".

**Comment by jwnimmer-tri** [comment] 2022-05-10 22:00
Okay, as best I can tell, this is a duplicate of #16978 -- we need to port show_model to use the new MeshcatVisualizer bindings.

Please comment or re-open in case there is a different problem I've overlooked.

**Comment by JoseBarreiros-TRI** [comment] 2022-05-11 22:20
@jwnimmer-tri It seems that the new meshcatvisualizer does not support capsule either.
when using:
`meshcat_vis = MeshcatVisualizerCpp.AddToBuilder(builder, scene_graph, meshcat)`

`WARNING:drake:Meshcat does not display Capsule geometry (yet).
WARNING:drake:Meshcat does not display Capsule geometry (yet).`

**Comment by jwnimmer-tri** [comment] 2022-05-11 22:22
That's true.  We can re-open this issue to track that request:

https://github.com/RobotLocomotion/drake/blob/bf5947f26b77b5c47d931814404de96d89ddca83/geometry/meshcat.cc#L305-L307

**Closed** 2022-11-02 17:12 UTC
Labels: component: geometry illustration
