### ISSUE TITLE
ROS CI Unable to Log and Test Results Directories Due to Insufficient Permissions

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3429] opened 2016-09-13 15:07 UTC
# Problem Definition

The error below was taken from: https://drake-jenkins.csail.mit.edu/job/linux-clang-experimental-ros/62/console

```
10:41:51 2: WARNING: cannot create log directory [/home/ubuntu/workspace/linux-clang-experimental-ros/log]. Please set ROS_LOG_DIR to a writable location.
10:41:52 2: Traceback (most recent call last):
10:41:52 2:   File "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest", line 36, in <module>
10:41:52 2:     rostestmain()
10:41:52 2:   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 273, in rostestmain
10:41:52 2:     _main()
10:41:52 2:   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain
10:41:52 2:     results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)
10:41:52 2:   File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file
10:41:52 2:     raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir))
10:41:52 2: IOError: cannot create test results directory [/home/ubuntu/workspace/linux-clang-experimental-ros/build/drake_ros_common_test/test_results/drake_ros_common_test]. Please check permissions.
```

The following error was taken from: https://drake-cdash.csail.mit.edu/testDetails.php?test=2652303&build=109867

```
WARNING: cannot create log directory [/home/ubuntu/workspace/linux-clang-experimental-ros/log]. Please set ROS_LOG_DIR to a writable location.
Traceback (most recent call last):
  File "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest", line 36, in <module>
    rostestmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 273, in rostestmain
    _main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain
    results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file
    raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir))
IOError: cannot create test results directory [/home/ubuntu/workspace/linux-clang-experimental-ros/build/drake_ros_common_test/test_results/drake_ros_common_test]. Please check permissions.
Cannot find results, writing failure results to '/home/ubuntu/workspace/linux-clang-experimental-ros/build/drake_ros_common_test/test_results/drake_ros_common_test/MISSING-rostest-test_simulation_abort_function_test.xml'
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ubuntu/workspace/linux-clang-experimental-ros/src/drake_ros_integration/drake_ros_common_test --package=drake_ros_common_test --results-filename test_simulation_abort_function_test.xml --results-base-dir "/home/ubuntu/workspace/linux-clang-experimental-ros/build/drake_ros_common_test/test_results" /home/ubuntu/workspace/linux-clang-experimental-ros/src/drake_ros_integration/drake_ros_common_test/test/simulation_abort_function_test.test 
-- run_tests.py: verify result "/home/ubuntu/workspace/linux-clang-experimental-ros/build/drake_ros_common_test/test_results/drake_ros_common_test/rostest-test_simulation_abort_function_test.xml"

```
# Question

Should environment variable `ROS_LOG_DIR` be set to a different location?

**Comment by liangfok** [comment] 2016-09-13 15:11
I'm going to elevate the priority of this issue to high because I just realized that it is causing #3409 to fail CI.

**Comment by jhoare** [comment] 2016-09-13 15:45
``ROS_HOME`` is set to be ``DASHBOARD_WORKSPACE`` which is where all jenkins build artifacts should be. https://github.com/RobotLocomotion/drake-ci/blob/master/ctest_driver_script_catkin.cmake#L110

**Comment by jhoare** [comment] 2016-09-13 16:03
It looks like re-running this in #3409 worked correctly, so it seems like there was something weird at the OS level?

**Comment by liangfok** [comment] 2016-09-13 16:04
Yes, something strange at the OS level. Since it passed the second time around, I'll downgrade the priority of this PR back to low.

**Comment by jwnimmer-tri** [comment] 2016-10-31 17:30
Maybe close this, as unreproducible?

**Comment by liangfok** [comment] 2016-11-05 20:17
This issue just occurred in #4040. I will leave it closed for now unless it becomes more problematic.

**Comment by liangfok** [comment] 2016-11-05 23:32
Since this issue just occurred in #4012 (https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/531/), I shall re-open this.

**Comment by liangfok** [comment] 2016-11-08 21:32
@hongkai-dai just encountered this issue here:

https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/653/consoleFull

**Comment by liangfok** [comment] 2016-11-23 10:06
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/1116/consoleFull

**Comment by jonathan-owens** [comment] 2016-11-29 01:26
https://drake-cdash.csail.mit.edu/testDetails.php?test=5050820&build=221987

**Comment by jonathan-owens** [comment] 2016-11-29 13:17
https://drake-cdash.csail.mit.edu/testDetails.php?test=5068729&build=222847

**Comment by liangfok** [comment] 2016-11-29 18:15
@SeanCurtis-TRI experienced this here:
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/1293/console

**Comment by Lucy-tri** [comment] 2016-12-05 17:21
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-gcc-nightly-matlab-ros/130/console

**Comment by liangfok** [comment] 2016-12-05 21:35
Again: https://drake-jenkins.csail.mit.edu/job/linux-gcc-continuous-ros-debug/722/console

**Comment by liangfok** [comment] 2016-12-06 00:44
Again: https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/1522/

**Comment by liangfok** [comment] 2016-12-27 12:28
Again: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-gcc-continuous-ros-debug/846/consoleFull

**Comment by mwoehlke-kitware** [comment] 2017-01-03 17:41
https://drake-jenkins.csail.mit.edu/job/linux-gcc-continuous-ros-release/881/

**Comment by liangfok** [comment] 2017-01-07 04:02
https://drake-jenkins.csail.mit.edu/job/linux-clang-continuous-ros-debug/954/

**Comment by liangfok** [comment] 2017-01-14 20:05
https://drake-jenkins.csail.mit.edu/job/linux-clang-continuous-ros-release/985/

**Comment by liangfok** [comment] 2017-01-16 05:09
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/2662/

**Comment by liangfok** [comment] 2017-01-16 23:11
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/2666/

**Comment by jonathan-owens** [comment] 2017-01-17 14:43
https://drake-jenkins.csail.mit.edu/job/linux-clang-nightly-ros-release/174/

**Comment by liangfok** [comment] 2017-01-18 02:07
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/2700/

**Comment by david-german-tri** [comment] 2017-01-26 22:54
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/2981/

**Comment by liangfok** [comment] 2017-02-13 19:42
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/3600

**Comment by liangfok** [comment] 2017-02-28 03:01
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/4203/

**Comment by liangfok** [comment] 2017-03-01 19:17
https://drake-jenkins.csail.mit.edu/job/linux-gcc-continuous-ros-debug/1215/

**Comment by liangfok** [comment] 2017-03-01 21:42
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/4296

**Comment by liangfok** [comment] 2017-03-24 16:30
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/5220

**Comment by liangfok** [comment] 2017-03-25 00:27
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/5252

**Comment by liangfok** [comment] 2017-03-26 03:29
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-clang-continuous-ros-debug/1447/

**Closed** 2017-08-15 19:08 UTC
Labels: configuration: ros, priority: low, team: kitware, type: bug
