### ISSUE TITLE
model directives: update or delete deprecation discussion

### ISSUE THREAD

**Issue by rpoyner-tri** [RobotLocomotion/drake#18061] opened 2022-10-10 17:34 UTC
There is a deprecation discussion around model directives that needs updating. Do we still intend to deprecate something? Is it the whole format? The older free-function API? What do we need to say about any of it?

See slack discussion: https://tri-internal.slack.com/archives/C02KXJ6LM54/p1665411954916569

**Comment by jwnimmer-tri** [comment] 2022-10-10 17:43
This is probably a duplicate of #15948.

Any deprecation has prerequisites that:
(1) our parser's support for SDFormat includes is complete and comprehensive, and
(2) we've provided a migration tool that takes in a DMD file and spits out the equivalent SDFormat file.

The existence of a fully-functional migration tool in (2) implies that (1) is also complete.

**Closed** 2022-10-19 22:05 UTC
Labels: type: feature request, component: multibody parsing
