### ISSUE TITLE
upgrade to gurobi 9

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#12987] opened 2020-04-02 16:21 UTC
Currently we support gurobi 8.0.1.

Can we support both gurobi 8 and gurobi 9? Their C++ API are compatible, and it is possible that some of our users have gurobi 8, but hasn't purchased gurobi 9 yet.

**Comment by jwnimmer-tri** [comment] 2020-04-03 23:42
Duplicate of #12419.

**Closed** 2020-04-03 23:53 UTC
Labels: team: kitware
