### ISSUE TITLE
cmake: Add option to disable building and installing pydrake

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13526] opened 2020-06-09 21:40 UTC
Per Slack request from @samzapo:
https://drakedevelopers.slack.com/archives/C0KDGF4V9/p1591737731088300

Plan of attack:
- [x] Try quick source-tree hack that does not install bindings
  - See Sam's comment here: https://github.com/RobotLocomotion/drake/issues/13526#issuecomment-641601123
- [ ] See if we can formalize this

**Comment by EricCousineau-TRI** [comment] 2020-06-09 21:40
Plan of attack:
- Try quick source-tree hack that does not install bindings
- See if we can formalize this

**Comment by EricCousineau-TRI** [comment] 2020-06-09 21:43
@samzapo Here's the one-liner hack:
https://github.com/EricCousineau-TRI/drake/commit/053a435e4a3d414090848727a55039eaab28d118

I'm briefly checking on my side.

Can you see if this works for you?

**Comment by samzapo** [comment] 2020-06-09 21:51
Yes, that fix worked for me.

**Comment by EricCousineau-TRI** [comment] 2020-06-09 21:56
Just to check, how are you consuming Drake from CMake?

The two options (from https://github.com/RobotLocomotion/drake-external-examples/tree/master/drake_cmake_external)
- `drake_cmake_installed` - Installing via Bazel to somewhere like `/opt/drake`
- `drake_cmake_external` - Using CMake `ExternalProject_Add` to consume Drake from source tree

**Comment by jamiesnape** [comment] 2020-06-09 21:57
Should be easy to formalize, I think. You can assign to me, if you like.

**Comment by EricCousineau-TRI** [comment] 2020-06-09 22:00
Done - thanks!

Only question in my mind is testing - I know we have an in-tree install test for the `drake_cmake_installed` worfklow, but nothing for the `drake_cmake_external` workflow (which makes total sense, come to think of it :P)

**Comment by samzapo** [comment] 2020-06-09 22:40
I'm using the `drake_cmake_installed` pattern.

**Comment by jwnimmer-tri** [comment] 2022-05-06 17:01
Resolving as a duplicate of #13526, which will attack the full problem.

**Closed by jwnimmer-tri** 2022-05-06 17:01 UTC
Labels: type: feature request, priority: low, component: build system
