### ISSUE TITLE
Better error messages when spatial inertias from file are not physical

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#11109] opened 2019-04-01 14:42 UTC
In #11094 @RussTedrake was getting a "non-physically valid" spatial inertia error message when loading a model from a URDF file. His initial thought was that the problem was with point masses since this model happened to have two point masses. However, further inspection revealed the problem was the "base" of the model had an inertia not satisfying the triangle inequality.

The error message however was not good enough to diagnose the problem without having to modify the URDF/dig in the code.

The proposed solution is to offer a better diagnosis message saying exactly what condition, for what body, was not satisfied.

**Comment by tri-ltyyu** [comment] 2019-04-29 20:24
If this issue is in progress, is there any update or next step? Thanks!

**Comment by jwnimmer-tri** [comment] 2021-11-12 01:28
This seems like a duplicate of #11109 at this point.

**Comment by sherm1** [comment] 2021-11-12 01:54
Agreed.

**Closed by sherm1** 2021-11-12 01:54 UTC
Labels: team: dynamics, priority: medium, component: multibody plant
