### ISSUE TITLE
Use gurobi 8.0.1 or 8.1.0

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#9829] opened 2018-10-27 16:14 UTC
Currently, Drake supports gurobi 8.0.0. But on gurobi website, they only provide download for gurobi 8.0.1 and 8.1.0 http://www.gurobi.com/downloads/gurobi-optimizer. We should upgrade our support on gurobi.

**Comment by jwnimmer-tri** [comment] 2018-10-27 16:36
Probably a duplicate of #9624 (or else, that one is a duplicate of this)?

**Comment by hongkai-dai** [comment] 2018-10-27 16:59
Thanks @jwnimmer-tri ! They are related. I think the solution in #9624 is to download gurobi from the link in https://github.com/RobotLocomotion/drake/issues/9624#issuecomment-428044725. On the other hand, we should test `GurobiSolver` with the newer version of Gurobi, possibly 8.1.0. Every upgrade of Gurobi fixes some problem, and likely also improve the performance. I plan to upgrade our GurobiSolver to support 8.1.0 once we finish refactoring MathematicalProgram.

**Comment by hongkai-dai** [comment] 2019-03-18 21:59
According to http://www.gurobi.com/products/whats-new/whats-new-in-the-latest-version, Gurobi 8.1 is significantly faster than Gurobi 8.0 for mixed integer problem. We should hence upgrade to this newer version.

**Comment by EricCousineau-TRI** [comment] 2019-04-25 14:40
Given that Jamie has #11269, reassigning.

**Comment by EricCousineau-TRI** [comment] 2019-05-09 14:51
Per f2f, should be up and coming.

**Closed** 2019-05-14 13:40 UTC
Labels: priority: medium, team: kitware, team: manipulation
