### ISSUE TITLE
Add unit tests for installation helpers

### ISSUE THREAD

**Issue by mwoehlke-kitware** [RobotLocomotion/drake#6117] opened 2017-05-16 19:44 UTC
#6072 adds some internal helper functions that probably should have some unit tests (`strip_prefix` in particular). For that matter, it would be nice to unit test `install` itself if the framework lets us do that. (Inspecting the returned actions for sanity should be sufficient, and can be done against a test project.)

**Comment by jwnimmer-tri** [comment] 2018-11-14 15:07
Closing as duplicate of #7331.

**Closed by jwnimmer-tri** 2018-11-14 15:07 UTC
Labels: configuration: bazel, team: kitware
