### ISSUE TITLE
Unused variable warning in testDrakeGeometryUtil

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#1722] opened 2016-02-17 16:55 UTC
See http://kobol.csail.mit.edu/cd/viewBuildError.php?type=1&buildid=21816.

**Comment by jwnimmer-tri** [comment] 2016-05-17 02:25
The top-post's link is dead now.  Closing as duplicate of #2372, anyway.

**Closed by jwnimmer-tri** 2016-05-17 02:25 UTC
Labels: priority: medium, team: software core, type: cleanup
