### ISSUE TITLE
pydrake's `OutputPort.Eval()` can cause segfaults

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9906] opened 2018-11-02 01:41 UTC
As discussed in #9902.

`OutputPort.EvalAbstract().get_value()` seems to work without the same hazard.

**Comment by EricCousineau-TRI** [comment] 2018-11-02 14:44
Duplicate of #9890, resolved by 12ff141

**Closed by EricCousineau-TRI** 2018-11-02 14:44 UTC
Labels: configuration: python, priority: medium, team: manipulation, type: bug
