### ISSUE TITLE
Better place for python GUI example

### ISSUE THREAD

**Issue by guzhaoyuan** [RobotLocomotion/drake#11649] opened 2019-06-14 16:23 UTC
![image](https://user-images.githubusercontent.com/11495993/59523138-5f2ba080-8e85-11e9-9e2e-6ba4d3943ef3.png)

https://github.com/RobotLocomotion/drake/blob/master/manipulation/util/geometry_inspector.py
is a GUI that we all love to use. But it is buried so deep that no one could find it. The usage example is in its comments (Difficult for user to use). 
I believe there should be an explicit example for this tool, maybe a README in the examples/ folder, or in the upcoming python tutorial.

**Comment by RussTedrake** [comment] 2019-06-21 14:07
i agree!  i was planning to include it (or a jupyter notebook equivalent) in my MBP tutorial that will land soonish on the drake main page.

**Comment by RussTedrake** [comment] 2021-09-19 22:42
Duplicate of #14980 .  (admittedly this one came first, but #14980 has the updated version of the resolution plan)

**Closed** 2021-09-19 22:42 UTC
Labels: team: manipulation, configuration: python, component: pydrake
