### ISSUE TITLE
CI coverage of pre-built drake visualizer

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#7050] opened 2017-09-19 12:33 UTC
Drake's CI should offer coverage of pre-built drake visualizer -- for example, that is launches without faults, that it runs for a few seconds without crashing, that it is able to locate data resources.  It is not unusual for users to experience problems running this software, so we should have CI coverage to point to that demonstrates that it works (and helps us keep regressions off of master).

Relates to #5621 as the feature to be tested in CI.

Relates to #6834 as an example of a scenario that should be tested in CI.

**Comment by jwnimmer-tri** [comment] 2018-11-14 15:19
Probably would be good enough to run it without opening a window, and then just immediately quit -- so that we test import / load paths.

**Comment by jamiesnape** [comment] 2018-11-14 15:20
It would if that we currently possible. We could however test the imports used by the launcher one level below.

**Comment by jwnimmer-tri** [comment] 2018-11-14 16:01
That SGTM to me too.

**Comment by EricCousineau-TRI** [comment] 2019-01-10 21:23
Just encountered an issue because this wasn't tested: We forgot to install the Python2.7 version of LCM, so now the installed `drake_visualizer` for `--config=python3` is broken.
However, I confirmed that `--help` doesn't catch this :(

We can just test imports in `drake_visualizer.py` wrappers as mentioned in #8324, but it means we won't catch install mistakes like this.

**Comment by EricCousineau-TRI** [comment] 2019-01-10 21:43
It would catch it for Bazel testing, but it wouldn't catch it at install, because we install the `drake-visualizer` binary, not a wrapper script.

**Comment by patmarion** [comment] 2019-01-11 08:20
hello!

is drake supporting python3 these days? if you're interested, there is python3 support for director.  it's not been merged to `master`, because there are still users of `master` stuck on python2, but you can get it here if needed- https://github.com/patmarion/director/tree/update-to-python3-ver5

**Comment by jamiesnape** [comment] 2019-01-11 13:35
Not on all platforms, so `drake-visualizer` is still Python 2.

**Comment by EricCousineau-TRI** [comment] 2019-05-16 14:36
Recent pain point: https://github.com/RobotLocomotion/drake/pull/11465#pullrequestreview-237565752

**Comment by EricCousineau-TRI** [comment] 2020-04-23 16:46
I want this to be narrowed down to just be `--help`.

**Comment by jamiesnape** [comment] 2020-04-23 21:46
`—help` still pops up a window that disappears straightaway, I think. Also if you look up in the comments, help was not sufficient (you said that, even).

**Comment by EricCousineau-TRI** [comment] 2020-04-23 21:48
I vaguely remembered something like that, but did not see the window when I ran it. Can I ask how you confirmed there's a window?

(If I run it on my machine, I see no window crop up, at least as of 629db0fcc on Ubuntu 18.04)

**Comment by EricCousineau-TRI** [comment] 2020-04-23 22:03
Looking at the code, I don't believe it currently starts a window (not sure what I encountered a year ago).

Tracing it out, my assumption is that the process exits before the app starts (which is responsible for instantiating the physical window on your WM?):
Parsing effectively happens through this (loosely identified) chain:
https://github.com/RobotLocomotion/director/blob/4c3e570a6797ff840c74067c742455daaa113d93/src/python/director/drcargs.py#L30-L33
https://github.com/RobotLocomotion/director/blob/4c3e570a6797ff840c74067c742455daaa113d93/src/python/director/drakevisualizerapp.py#L32-L36

So I think we're good?

**Comment by EricCousineau-TRI** [comment] 2020-04-23 22:13
Also confirmed that Drake Viz will fail if it can't access a display, even on these simplified codepaths, so maybe `--help` is more-than-decent enough test?
```
env DISPLAY=: ./bazel-bin/tools/drake_visualizer --help
```

**Comment by jamiesnape** [comment] 2020-04-24 13:21
I think it is useful, so I have no problem with us having that test initially. I would need to go through the issues to remind myself what the main point of failure was. OS and VTK upgrades are high risk for `drake-visualizer`, so now is the time to add something.

**Closed** 2020-04-29 02:54 UTC
Labels: component: continuous integration, priority: medium, team: kitware
