### ISSUE TITLE
Numerical instability of PiecewiseQuaternionSlerp

### ISSUE THREAD

**Issue by rcywongaa** [RobotLocomotion/drake#14561] opened 2021-01-24 07:39 UTC
Consider the following program
```
from pydrake.all import PiecewiseQuaternionSlerp, Quaternion
import numpy as np

q1 = np.array([1.0, 0.0, 0.0, 0.0])
q2 = np.array([-0.5, -0.5, 0.5, 0.5])
slerp1 = PiecewiseQuaternionSlerp(breaks=[0, 1], quaternions=[Quaternion(q1), Quaternion(q2)])
for i in np.linspace(0, 1, 11):
    print(f"1: {Quaternion(slerp1.value(i)).wxyz()}")

q3 = np.array([1.0, 0.0, 0.0, 0.0])
q4 = np.array([-0.5, -0.5, 0.4999999999999999, 0.5000000000000001])
slerp2 = PiecewiseQuaternionSlerp(breaks=[0, 1], quaternions=[Quaternion(q3), Quaternion(q4)])
for i in np.linspace(0, 1, 11):
    print(f"2: {Quaternion(slerp2.value(i)).wxyz()}")
```
Output:
```
1: [1. 0. 0. 0.]
1: [ 0.9945219   0.06034954 -0.06034954 -0.06034954]
1: [ 0.9781476   0.12003787 -0.12003787 -0.12003787]
1: [ 0.95105652  0.17841104 -0.17841104 -0.17841104]
1: [ 0.91354546  0.23482951 -0.23482951 -0.23482951]
1: [ 0.8660254   0.28867513 -0.28867513 -0.28867513]
1: [ 0.80901699  0.33935797 -0.33935797 -0.33935797]
1: [ 0.74314483  0.38632274 -0.38632274 -0.38632274]
1: [ 0.66913061  0.42905487 -0.42905487 -0.42905487]
1: [ 0.58778525  0.46708618 -0.46708618 -0.46708618]
1: [ 0.5  0.5 -0.5 -0.5]
2: [1. 0. 0. 0.]
2: [ 0.9945219   0.06034954 -0.06034954 -0.06034954]
2: [ 0.9781476   0.12003787 -0.12003787 -0.12003787]
2: [ 0.95105652  0.17841104 -0.17841104 -0.17841104]
2: [ 0.91354546  0.23482951 -0.23482951 -0.23482951]
2: [ 0.8660254   0.28867513 -0.28867513 -0.28867513]
2: [ 0.80901699  0.33935797 -0.33935797 -0.33935797]
2: [ 0.74314483  0.38632274 -0.38632274 -0.38632274]
2: [ 0.66913061  0.42905487 -0.42905487 -0.42905487]
2: [ 0.58778525  0.46708618 -0.46708618 -0.46708618]
2: [-0.5 -0.5  0.5  0.5]
```

While I'm aware that `[0.5, 0.5, -0.5, -0.5]` and `[-0.5, -0.5, 0.5, 0.5]` represent the same rotation, it seems unintuitive that the slerp will return quaternions with a large jump in element values.

This was tested with the latest v0.26.0 release

### Edit

Here's another manifestation I stumbled upon:

```
from pydrake.all import PiecewiseQuaternionSlerp, Quaternion
import numpy as np

q1 = np.array([1.0, 0.0, 0.0, 0.0])
q2 = np.array([
    4.329780281177466e-17,
    0.7071067811865475,
    -0.7071067811865476,
    -1.2989340843532398e-16])

dt = 0.02631578947368421
slerp1 = PiecewiseQuaternionSlerp(breaks=[0, 20*dt], quaternions=[Quaternion(q1), Quaternion(q2)])
for i in range(20):
    print(f"{i}: {Quaternion(slerp1.value(i*dt)).wxyz()}")
```
Output:
```
0: [1. 0. 0. 0.]
1: [ 9.96917334e-01  5.54789586e-02 -5.54789586e-02 -1.00055036e-17]
2: [ 9.87688341e-01  1.10615871e-01 -1.10615871e-01 -2.10761643e-17]
3: [ 9.72369920e-01  1.65070800e-01 -1.65070800e-01 -2.85442557e-17]
4: [ 9.51056516e-01  2.18508012e-01 -2.18508012e-01 -4.37759089e-17]
5: [ 9.23879533e-01  2.70598050e-01 -2.70598050e-01 -4.50636278e-17]
6: [ 8.91006524e-01  3.21019761e-01 -3.21019761e-01 -6.23016215e-17]
7: [ 8.52640164e-01  3.69462278e-01 -3.69462278e-01 -6.51050156e-17]
8: [ 8.09016994e-01  4.15626938e-01 -4.15626938e-01 -6.86155564e-17]
9: [ 7.60405966e-01  4.59229119e-01 -4.59229119e-01 -7.30019933e-17]
10: [ 7.07106781e-01  5.00000000e-01 -5.00000000e-01 -7.85046229e-17]
11: [ 6.49448048e-01  5.37688215e-01 -5.37688215e-01 -8.54743522e-17]
12: [ 5.87785252e-01  5.72061403e-01 -5.72061403e-01 -9.44412113e-17]
13: [ 5.22498565e-01  6.02907642e-01 -6.02907642e-01 -1.06241730e-16]
14: [ 4.53990500e-01  6.30036755e-01 -6.30036755e-01 -8.81077981e-17]
15: [-3.82683432e-01 -6.53281482e-01  6.53281482e-01  1.06215989e-16]
16: [-3.09016994e-01 -6.72498512e-01  6.72498512e-01  1.23816968e-16]
17: [-2.33445364e-01 -6.87569365e-01  6.87569365e-01  1.21103020e-16]
18: [-1.56434465e-01 -6.98401123e-01  6.98401123e-01  1.19224789e-16]
19: [-7.84590957e-02 -7.04927007e-01  7.04927007e-01  1.27964484e-16]
```

**Comment by SeanCurtis-TRI** [comment] 2021-01-25 14:45
@RussTedrake As the primary author of this code (at least as far as the existing history knows), I'm assigning this to you. Feel free to pass it along as appropriate.

**Comment by RussTedrake** [comment] 2021-01-25 16:34
Actually, I only touched the API... @siyuanfeng-tri is the real author.  @siyuanfeng-tri , want to take a look?

**Comment by siyuanfeng-tri** [comment] 2021-01-26 06:30
sure.

**Comment by siyuanfeng-tri** [comment] 2021-01-26 17:17
Thanks for reporting this.
The issue is coming from you getting the interpolated Quaternion as a matrix (through `slerp2.value(t)`) then converting it to quaternion with Eigen's constructor. Because we didn't expose the full c++ API to python for getters like this https://github.com/RobotLocomotion/drake/blob/master/common/trajectories/piecewise_quaternion.h#L91, which doesn't have this issue.. I will need to submit a patch to expose those.

FYI, drake's matrix to quaternion conversion does force a sign choice for quaternions, https://github.com/RobotLocomotion/drake/blob/master/math/rotation_matrix.h#L587. You could use that if that's appropriate.

**Comment by siyuanfeng-tri** [comment] 2021-01-28 04:37
should be patched.

**Closed by siyuanfeng-tri** 2021-01-28 04:37 UTC
Labels: team: manipulation
