### ISSUE TITLE
village-demo broken on master?

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#5704] opened 2017-04-03 12:26 UTC
after a clean build/install on xenial, running `bazel run drake/automotive:village-demo` resulted in 

```
...
[dev_demo] Welding joint front_lidar_joint
[dev_demo] Welding joint top_lidar_joint
[dev_demo] Welding joint rear_right_lidar_joint
[dev_demo] Welding joint rear_left_lidar_joint
[dev_demo] terminate called after throwing an instance of '
[dev_demo] std::runtime_error
[dev_demo] '
[dev_demo]   what():  
[dev_demo] CarVisApplicator::DoCalcOutput(): Input PoseBundle has 0poses. Expected 15.
[lcm-logger] Summary: lcmlog-2017-04-03.00 ti:   2sec Events: 5         (    0 MB )      TPS:     2.73       KB/s:    30.00
[automotive_demo.py] dev_demo exited -6
```

apologies in advance if it's user error!

**Comment by RussTedrake** [comment] 2017-04-03 12:29
not surprising, but the merging demo has the same problem.

**Comment by liangfok** [comment] 2017-04-03 12:45
I know what the problem is. `AutomotiveSimulator<T>::AddPriusEndlessRoadCar()` is not connecting the `EndlessRoadCar` to the `PoseAggregator`. I shall self-assign and fix this with high priority.

**Comment by liangfok** [comment] 2017-04-03 12:47
Maybe a better fix for this is to replace the `EndlessRoadCar` with `MaliputRailcar`? There are still some kinks to work out regarding `MaliputRailcar`'s lane transitions. They are being worked out in #5699. I'll see which one gets into master first.

**Comment by jwnimmer-tri** [comment] 2017-04-03 12:50
I am going to `git rm` the village / endless code now.  If we want to make a video of it, we should use a commit from when it went in.

**Closed** 2017-04-03 15:22 UTC
Labels: priority: high, team: cars, type: bug
