### ISSUE TITLE
Bazel (and cmake) compilation fails

### ISSUE THREAD

**Issue by gstavrinos** [RobotLocomotion/drake#9238] opened 2018-08-07 16:25 UTC
Ubuntu 18.04, after installing all the prerequisites using the script provided, I get both with bazel and cmake the following error:

`ERROR: /home/gstavrinos/drake/geometry/BUILD.bazel:55:1: C++ compilation of rule '//geometry:frame_kinematics' failed (Exit 1)
In file included from bazel-out/k8-opt/bin/common/_virtual_includes/autodiff/drake/common/autodiff.h:31:0,
                 from geometry/frame_kinematics_vector.cc:8:
bazel-out/k8-opt/bin/common/_virtual_includes/autodiff/drake/common/autodiffxd.h: In constructor 'drake::geometry::FrameKinematicsVector<KinematicsValue>::FrameKinematicsVector(drake::geometry::SourceId, const std::vector<drake::geometry::Identifier<drake::geometry::FrameTag> >&) [with KinematicsValue = Eigen::Transform<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1> >, 3, 1, 0>]':
bazel-out/k8-opt/bin/common/_virtual_includes/autodiff/drake/common/autodiffxd.h:103:26: error: '*((void*)&<anonymous> +16)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     m_value = other.value();
`

**Comment by soonho-tri** [comment] 2018-08-07 16:32
FYI, this problem was reported in https://github.com/RobotLocomotion/drake/pull/9216. AFAIK, @SeanCurtis-TRI is working on a fix.

**Comment by gstavrinos** [comment] 2018-08-07 16:40
Thanks for the prompt reply. I search for something similar, but github search was not helpful. I will keep an eye on that issue!

**Comment by jwnimmer-tri** [comment] 2018-08-07 16:41
Duplicate of #9233.

**Closed by jwnimmer-tri** 2018-08-07 16:41 UTC
