### ISSUE TITLE
more robust support for different mesh formats on different visualizers

### ISSUE THREAD

**Issue by tdinesh** [RobotLocomotion/drake#561] opened 2014-11-14 22:51 UTC
Hi

I am getting the following error when trying to load the atlas_v3.urdf generated using xacro and `atlas_description/robots/atlas_v3.urdf.xacro`. 

Error using RigidBodyMesh/loadFile (line 37)
Invalid STL file
"/opt/ros/hydro/share/atlas_description/urdf/meshes_v3/pelvis.stl".

Any thoughts? The meshes under `/opt/ros/hydro/share/atlas_description/urdf/meshes` do not give error. Is there a working v3 urdf?

Thanks!

**Comment by RussTedrake** [comment] 2015-02-01 12:43
This is also related to #629 .

**Comment by RussTedrake** [comment] 2015-04-21 21:14
closing now as duplicate of #629 and #1018 .

**Closed by RussTedrake** 2015-04-21 21:14 UTC
